### PR TITLE
Updated License

### PR DESCRIPTION
**Pull request by AzureMarker**
Replaces MIT with GPLv2 and adds header to api.php and index.php.
Everything that we create that was not covered under MIT (the AdminLTE stuff) is covered under GPLv2.

### CODE REVIEW

**Comment by dschaper** [comment]
I'm not sure if we need to include both licenses or not? Do we contact @almasaeed2010 to find out what would be the best route? (I guess the mention here automatically contacts him!)

**Comment by Lewiscowles1986** [comment]
can I ask if AGPL could be considered? GPL for server-based SW only affects those with server access back-end AFAIK, whereas AGPL affects anyone using the SW, even a user

**Comment by dschaper** [comment]
I like what I'm reading about Affero. @Lewiscowles1986 I don't think we'd need to do anything different on our end to implement it, since we have to distribute all the source code to make the scripts work anyways, there's no compiled or blobbed code, from what I can tell? Any thoughts on that?

**Comment by Lewiscowles1986** [comment]
AGPL is not only about the people that need to deploy the code; it covers access to code for any user of the program (say a visitor to a website, or user of pi-hole's admin interface in this case). I can see where the confusion is, but the user wouldn't be guaranteed source code access under MIT or GPL AFAIK, just the administrator of the pi-hole.

**Comment by dschaper** [comment]
Do we have a requirement other than posting the code here on GitHub? Would we be required to provide the source in a way that's available to the end users on each installation? (Would we have to include a tarball with the source with our releases and create a way (say by url) for the end user to be able to grab the tarball from the Pi-Hole end node installation? Or can we as the parent of the source tree just rely on the fact that all the code is available here on GitHub and there is no change when people initially download the code from here?) 

How do we benefit from AGPL, are our direct end users and any downstream end users required to share their changes back upstream all the way to us? Or is this more like saying, if the direct downloader of the Pi-Hole scripts changes anything, they are then required to make those changes available to their end users, if they wanted them? So an end user would be able to see the code that is running on the Pi-Hole end node installation and be able to compare it to the source here on GitHub and diff any changes made while traversing the tree from "pristine" source here to implemented source at the end node?

**Comment by Lewiscowles1986** [comment]
to put it shortly regarding users making their own changes available 

image

Yes :+1:

**Comment by dschaper** [comment]
Great! Thanks for the pointer to the license, would never have found it otherwise!

**Comment by Lewiscowles1986** [comment]
Sorry, here is a link, but you didn't ask for it buddy, just what different requirements it would have
 
https://www.gnu.org/licenses/agpl-3.0.en.html

**Comment by jacobsalmela** [comment]
Closing due to #402

**Pull request closed without merging**
