### PR TITLE
Update codeql.yml

### PR DESCRIPTION
**Pull request by XhmikosR**
**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [ ] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

### CODE REVIEW

**Comment by XhmikosR** [comment]
Needs a squash when merging.

**Comment by PromoFaux** [comment]
@XhmikosR this is missing the DCO signoff, please fix that

**Comment by XhmikosR** [comment]
Can't do that, I edited through GitHub.

**Comment by PromoFaux** [comment]
```
cd path/to/adminlte/repo/locally #failing it already existing - clone and checkout
git checkout XhmikosR-patch-1
git rebase HEAD~2 --signoff
git push --force-with-lease origin XhmikosR-patch1
```

for future reference you can add the signoff line in manually when editing via the github web

**Comment by XhmikosR** [comment]
I'm aware how to fix it, I just don't go through this dance. Feel free to drop the PR or just ignore the bot.

**Comment by PromoFaux** [comment]
Fine. If you're going to be lazy.

**Pull request closed without merging**
