### PR TITLE
Modal-Dialog for Teleporter-import

### PR DESCRIPTION
**Pull request by Th3M3**
**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [ ] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

Using a Modal Dialog for Teleporter Import status.
Fix addressed issue in another PR' comment, where the settings page reloads every time the DHCP tab gets active.

**How does this PR accomplish the above?:**

Embedd an `iframe` in the Modal Dialog and load the `teleporter.php` into this iframe.
This makes the output accessible, so that after importing `static DHCP leases` the user can be warned that the page needs to be reloaded.

**What documentation changes (if any) are needed to support this PR?:**

`/`

teleporter_Modal

### CODE REVIEW

**Comment by Th3M3** [comment]
By the way, two more things:
- `settings.js` should cleaned up later.
There are two `$(function() {...})` and three `$(document).ready(function() {...})` functions wich all get called when the document is loaded. They should be merged for better clarity.

- `<div id=token hidden>...</div>` is specified twice on each page (with the same token) after the `<noscript>` tag.

**Comment by PromoFaux** [comment]
Very like this idea, however I'm getting the following:

image

**Comment by Th3M3** [comment]
Ok, I see now what I've missed.

In `lighttpd.conf`, `X-Frame-Options: DENY` is set for path `/admin/`.
But I was using another path for testing.

We would need to add the following to `lighttpd.conf` to allow the iframe on the settings page, if there are no security concerns about this:
```apacheconf
    # allow teleporter iframe on settings page
    $HTTP["url"] =~ "/teleporter\.php$" {
        $HTTP["referer"] =~ "/admin/settings\.php" {
            setenv.add-response-header = ( "X-Frame-Options" => "SAMEORIGIN" )
        }
    }
```

**Comment by XhmikosR** [comment]
> ```
> <div id="token" hidden>...</div>
> ```
> 
> is specified twice on each page (with the same token) after the <noscript> tag.
> ```

Yeah I noticed that also. I have an untested branch but please make a new issue so that we don't forget about it.

**Comment by XhmikosR** [comment]
BTW personally I don't like using iframes. The native browser function is the most secure and simpler option IMHO.

**Comment by PromoFaux** [comment]
Sorry @theme, I've switched the target branch to `devel` as this obviously didn't make the cut in time for 5.0. Could you please resolve the merge conflict here? Thanks!

**Comment by Th3M3** [comment]
@PromoFaux 
Ok, done.
I've also fixed my code format errors in `settings.js` wich now were pointed out by Workflow `Tests / Node 12`.

**Comment by PromoFaux** [comment]
Great, thanks @Th3M3 . Did you want to open a PR against the `lighttpd.conf` in core, too?

@XhmikosR, could you explain the following please (for those of us like myself who are of a "this works, so I don't see anything wrong with it" mindset)

>The native browser function is the most secure and simpler option IMHO.

**Comment by XhmikosR** [comment]
First of all, don't get me wrong, I'm the one who made the comment about the page reload which is wrong. I also have #1318 for this, so I'd really like to get this sorted out.

That being said,

1. I don't quite see the need for going through all this trouble, but I haven't quite followed why it's needed to reload the page. Can someone explain to me why we need the page to reload in the first place?
2. Using a modal for something that browsers support natively, like the browse dialog, seems like a total hack to me. If there is no other way to work around the issue, then, of course, this will be a candidate, but see my previous point

A few probably nitpicking comments, but...

1. Not a big fan of breaking the lines between attributes; there's line wrap in editors :)
2. The IDs is better if they are meaningful and not for example `exampleModalLabel`. We don't run an HTML validator and things like that can bite us in the ass later
3. `col-xs-12` isn't supposed to be used in random elements, only after a `.row`
4. The label should be a heading
5. Why not allow to close the modal with keyboard?
6. I'd add a modal close button to the top right as per the docs
7. Not sure `pre` inside the modal is a good choice, but maybe if you use a bigger height it'll be better (200 or 300)
8. Should probably be cleared after a successful restore?
9. Which reminds me, the `Restore` button should be disabled if no file is loaded (happens in dev too)

Nevertheless, thanks for taking the time to tackle this! My first two points are so that I understand the situation better, and for the rest I could help if needed.

**Comment by Th3M3** [comment]
The page reload has been implemented (not by me) to reload the imported DHCP leases table (and may other changed settings) after a teleporter import.

I am not a Pro, my idea was to use the iframe and check the output for a marker to reload the page only if relevant settings has been changed by the import.

But surely this can also be solved differently, without Hack.

**Comment by XhmikosR** [comment]
We should postpone this for after 5.1.0 is out to avoid conflicts.

**Comment by DL6ER** [comment]
This does not seem to work:
Screenshot at 2020-12-10 22-19-39

Full text:

> ## Firefox Can’t Open This Page
>
> To protect your security, pi.hole will not allow Firefox to display the page if another site has embedded it. To see this page, you need to open it in a new window.

**Comment by DL6ER** [comment]
Okay, this seems to work as intended. The colors are off in the dark web interface but we can address this in a follow-up PR as it is unrelated to what we're dealing here with.

Screenshot at 2020-12-10 23-12-36

**Review by DL6ER — CHANGES_REQUESTED** [review]
This feature can only be merged when the necessary changes to `lighttpd.conf` have been added to the core repository

**Comment by PromoFaux** [comment]
Rebased on latest devel and addressed complaints from prettier

**Comment by PromoFaux** [comment]
(Sorry it's been so long @Th3M3!)

@DL6ER please see https://github.com/pi-hole/pi-hole/pull/4375

**Review by DL6ER — APPROVED** [review]

**Pull request merged**
