### PR TITLE
Add per-browser styling settings

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
**What does this PR aim to accomplish?:**

- Add per-browser styling settings
- Use iCheck-bootstrap instead of iCheck2

**How does this PR accomplish the above?:**

A picture says more than thousand words:
Screenshot from 2020-06-02 16-03-38

**What documentation changes (if any) are needed to support this PR?:**

None

### CODE REVIEW

**Comment by PromoFaux** [comment]
So, I rebased this on devel and the checks are now passing

**Comment by PromoFaux** [comment]
OK, it was me in the last commit... what did I do there?

**Review by PromoFaux — APPROVED** [review]

**Comment by yubiuser** [comment]
On Chrome
Bildschirmfoto zu 2020-06-03 22-04-51


On Firefox
Bildschirmfoto zu 2020-06-03 22-04-39


Notice how the box expands upwards and touches the menu bar, almost hiding the first enty.

**Comment by DL6ER** [comment]
@yubiuser per-browser behavior with built-in elements like select menus may be very hard, if at all possible, modifiable in a consistent manner

**Pull request merged**
