### PR TITLE
Add dependabot config

### PR DESCRIPTION
**Pull request by XhmikosR**
Ignore coreui 3.x and react-table 7.x packages

Hopefully this will ignore the aforementioned updates until someone adapts the codebase.

### CODE REVIEW

**Comment by Mcat12** [comment]
If Dependabot makes a PR to update the versions, sending a `@dependabot ignore this major version` command will do the same thing but without having to maintain a config file or go through the PR process.

**Comment by XhmikosR** [comment]
Not exactly the same. I'd rather ignore all new versions of a library than
closing multiple PRs. Until/if ever the dependencies are updated.

**Comment by XhmikosR** [comment]
Oh, wait, you said ignore major version. I will check out the docs tomorrow.

**Comment by Mcat12** [comment]
There's a lot of granularity. You can ignore the next major/minor update, all updates, only the update in the PR, etc. Each Dependabot PR has a list of commands that you can use at the bottom. See the latest PR for an example: #661

**Comment by XhmikosR** [comment]
And how does one un-ignore a dep if it's ignored via a comment?

**Comment by XhmikosR** [comment]
Let's try it your way. I guess one needs to update the ignored deps manually for dependabot to start checking for them again.

**Comment by Mcat12** [comment]
Un-ignoring is done by re-opening the PR:
> `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)

**Pull request closed without merging**
