### PR TITLE
Update Dashboard and Login Screen images

### PR DESCRIPTION
**Pull request by rdwebdesign**
### What does this PR aim to accomplish?

Update _Dashboard_ and _Login Screen_ images

### How does this PR accomplish the above?

Replacing the images

Pi-hole Web interfacePassword protection

### What documentation changes (if any) are needed to support this PR?

none

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
- [x] I have read the above and my PR is ready for review. _Check this box to confirm_

### CODE REVIEW

**Comment by yubiuser** [comment]
Can we delete the old screenshots or are they used somewhere else?

**Comment by rdwebdesign** [comment]
I didn't deleted them because I have the same doubt.

**Comment by dschaper** [comment]
I'm sure they are being used somewhere like a blog post or something. It's not harming anything to keep them.

**Review by yubiuser — COMMENTED** [review]
Scaling on mobile is a bit strange
Screenshot at 2022-09-17 10-12-39

**Comment by rdwebdesign** [comment]
> Scaling on mobile is a bit strange

I think this is happening in the `master` branch too.

**Comment by yubiuser** [comment]
It does, but now might be a good time to change it 😜

**Comment by rdwebdesign** [comment]
:unamused:
Of course.
What made you think I was planing to leave it like this?

Are you implying I'm that lazy?
:joy:

**Review by yubiuser — APPROVED** [review]

**Pull request merged**
