### PR TITLE
Include csp img-src data

### PR DESCRIPTION
**Pull request by xopez**
**By submitting this pull request, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [ ] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

Currently the background image of the dark-midnight theme isn't loaded due to insufficient csp configuration, causing it to be blocked.

**How does this PR accomplish the above?:**

The image is loaded via direct data in css (https://github.com/pi-hole/AdminLTE/blob/master/style/themes/default-darker.css#L5641). So we just need to extend the csp header to allow it.

**What documentation changes (if any) are needed to support this PR?:**

Nothing I think.

----
Since I am using github web for this commit I don't know how to "Sign Off" the commit.

### CODE REVIEW

**Comment by dschaper** [comment]
Your comment is enough for me. I've set DCO to pass.

**Comment by xopez** [comment]
To extend it a bit more:
We should not at it to every theme. So I wanna change it to `<?php if ($theme == "default-darker") echo 'data:' ?>`
But I need an opinion on that.

**Comment by PromoFaux** [comment]
> But I need an opinion on that.

Is the issue _only_ seen on the `default-darker` theme?

**Comment by xopez** [comment]
> > But I need an opinion on that.
> 
> Is the issue _only_ seen on the `default-darker` theme?

Yes. It isn't needed on the other themes.

**Comment by PromoFaux** [comment]
Ah, gotcha.. then yeah, feel free to make it conditional

**Comment by xopez** [comment]
I have made the change.

**Comment by yubiuser** [comment]
This PR does fix the background issue.

Bildschirmfoto zu 2021-10-05 12-45-11
Bildschirmfoto zu 2021-10-05 12-46-59

However, I'm not sure if this is the best way to fix the issue. Why not include the background image as in the other themes as 

```
.layout-boxed {
  background: url("../../img/boxed-bg-dark.jpg") repeat fixed;
```

This is much simpler to read and would make the code more homogeneous. This would avoid introducing a special theme depended header.

**Comment by PromoFaux** [comment]
> . Why not include the background image as in the other themes

It's a good question. @DL6ER ?

**Comment by DL6ER** [comment]
A question I cannot answer because I don't remember (too long ago). Maybe I just thought it's "nicer" at that time.
Feel free to use whatever you prefer / think is easiest.

**Comment by PromoFaux** [comment]
I think @yubiuser makes a fair point that it would be tidier/easier to see what was going on.

My vote: it should be consistent across all the themes, whichever method is decided on.

**Comment by xopez** [comment]
I agree with that.

**Comment by rdwebdesign** [comment]
I have a suggestion:

Use this CSS for the _default-darker_ theme:
```CSS
.layout-boxed {
    background: linear-gradient(rgba(20, 30, 34, .6), rgba(20, 30, 34, .6)), url(../../img/boxed-bg-dark.jpg) fixed;
}
```

This way, the theme will use the same background image (already used for the _default-dark_ theme), but with a semi-transparent dark layer on top. No need for an extra file.

**Comment by yubiuser** [comment]
@xopez 

Are you going to work on this?

**Comment by xopez** [comment]
> @xopez
> 
> Are you going to work on this?

Yes, I just waited for a few feedback posts and opinions.


> I have a suggestion:
> 
> Use this CSS for the _default-darker_ theme:
> 
> ```css
> .layout-boxed {
>     background: linear-gradient(rgba(20, 30, 34, .6), rgba(20, 30, 34, .6)), url(../../img/boxed-bg-dark.jpg) fixed;
> }
> ```
> 
> This way, the theme will use the same background image (already used for the _default-dark_ theme), but with a semi-transparent dark layer on top. No need for an extra file.

I have just tested this and it works fine. I will change this.

**Comment by PromoFaux** [comment]
It might be easier to start with a fresh pull request - as it looks like codefactor has decided everything is not so good! 

RE: signing off your commit when using the web interface, just add `Signed-off-by: xopez <xopez@users.noreply.github.com>` at the end of your commit message (on a new line)

**Comment by xopez** [comment]
I have made I have created a new PR. That is why I am closing this one.

**Pull request closed without merging**
