### PR TITLE
Improved loop for getAllQueries

### PR DESCRIPTION
**Pull request by rdwebdesign**
**By submitting this pull request, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

This PR reduces the memory needed by `api_db.php?getAllQueries` to process every requested record. 

**How does this PR accomplish the above?:**

The current code used to generate and return the request adds all records into a single array. This array grows for each record (and there are many many records).
Only at the end (and if memory holds up), it transforms the entire array into JSON and sends all at once as a string.

The new code outputs each record as a string immediately.
This way, there is no array and the memory for each iteration is always the same.
The web server is responsible for sending the "text stream", nothing else needs to change.

**What documentation changes (if any) are needed to support this PR?:**

None.

### CODE REVIEW

**Comment by DL6ER** [comment]
Does this output in chunks instead of one big output suggest adding `header("Transfer-Encoding: chunked");` ?

**Comment by rdwebdesign** [comment]
The problem here is not exactly how the page outputs the result.

The problem is how much memory the page needs during the process.

The old code holds ALL data in memory during the entire `while` loop.
Each loop iteration adds a new item to the array (the array grows). 
At the end of the loop, there is a **huge** array in memory. 
Only after the loop the page processes the array and outputs the result.
There will be no memory gain using "chunked" output, because the memory was already full.

The new code outputs one record at a time.
Each loop iteration holds **only the current record** in memory. The memory use is very lower.

**Comment by DL6ER** [comment]
> The new code outputs one record at a time.

Yes, hence my question because this is now chunked.

**Comment by rdwebdesign** [comment]
For PHP this won't change anything. 
This header forces the _web server_ to send a "chunked" response.

As far as I know, Lighttpd automatically uses `server.stream-response-body = 1` if needed.

**Review by PromoFaux — APPROVED** [review]

**Pull request merged**
