### PR TITLE
Change radius to 10px for a more modern look.

### PR DESCRIPTION
**Pull request by Gontier-Julien**
Signed-off-by: Gontier Julien <gontierjulien68@gmail.com>

**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

It make the interface look a bit more modern not much but improve the overall visual experience.

**How does this PR accomplish the above?:**

-Change `.small-box` and `.box` from `border-radius:3px` to `border-radius:10px`.

**What documentation changes (if any) are needed to support this PR?:**

None

### CODE REVIEW

**Review by DL6ER — DISMISSED** [review]
Can this be realized without changes in `vendor` directories (like ` style/vendor`)?

The reason I'm asking is basically two-fold:
- Due to the licenses of the contained third-party software, changes often have to be submitted upstream
- Ont he next update of the component, we will have forgotten about this change and simply replace this file with its updated version - undoing your changes unintentionally.

Overwrites are added in `style/pi-hole.css`, typically where they are guaranteed to stay in our open license and won't be overwritten on component upgrades.

This may also apply to your other PRs, I haven't had the time to look at them so far.

**Comment by Gontier-Julien** [comment]
How right sorry about that i while fix this today, i didn't pay attention to this ^^'
Do you want me to make a new pull request to this ?

**Comment by Gontier-Julien** [comment]
Wrong button*

**Comment by DL6ER** [comment]
No worries, you can either reuse this PR by undoing your first commit and making a new one + force-push. Or just add the change in a second commit which we can then squash-merge. The latter is probably the easiest.

**Comment by Gontier-Julien** [comment]
Okay no problems i will reuse this PR request and remove this commit and make a new one.

**Comment by Gontier-Julien** [comment]
Sorry about this inconvenience ^^' but now it fixed ^^

**Review by PromoFaux — APPROVED** [review]

**Comment by dschaper** [comment]
@Gontier-Julien What is your background for front end? Are you familiar with any frameworks?

**Comment by Gontier-Julien** [comment]
@dschaper i currently don't "have" a background in this, but i've had worked for two small enterprise where i've done there interface and helped the dev team. I'm still a student at the moment.
And no i don't have any experience in frameworks, but i can still learn.

**Comment by dschaper** [comment]
I'm very happy to have you contribute and learn as you go, so please don't let that be a barrier to your continuing to contribute. We don't ask for resumes or CVs to contribute, your work speaks for you in that regard.

Front-end design is very much a personal preference for a lot of things but we do come to a consensus almost all of the time.

**Comment by Gontier-Julien** [comment]
Thank you very much ^^
event if i'm still struggling in back-end, i'm rock solid on the frond-end.
If you need any help for the Soon™ design i will be happy to help out ^^

**Pull request merged**
