### PR TITLE
Use xo 0.53.0 and fix errors

### PR DESCRIPTION
**Pull request by yubiuser**
**What does this PR aim to accomplish?:**

Supersedes https://github.com/pi-hole/AdminLTE/pull/2435 by incorporating necessary error fixes.

We need to decide if we want to use the "new" styles for  `unicorn/switch-case-braces`, `unicorn/prefer-logical-operator-over-ternary` and `prefer-regex-literals`.

https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/switch-case-braces.md
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-logical-operator-over-ternary.md
https://eslint.org/docs/latest/rules/prefer-regex-literals

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by rdwebdesign** [comment]
As this is labeled as a Discussion, I think we can add our opinions about each option:

- `unicorn/switch-case-braces`: 🚫  I'm not sure if this is needed. Personally I don't think we need braces.

- `unicorn/prefer-logical-operator-over-ternary`: 🚫 I don't like this option.
    I don't like to force a "preference" in code writing (it's called `prefer-`). 
    It's a very confusing option:
    This is considered invalid: `foo ? foo : bar;`
    but this is considered valid: `foo ? bar : baz;`

- `prefer-regex-literals`: ✔️  I think we already use literals almost everywhere.

**Comment by yubiuser** [comment]
I totally agree with not using `unicorn/prefer-logical-operator-over-ternary`. This makes it harder to read the code and esp. the `nullish coalescing operator` gives me a headache.

I have no special feelings regarding `unicorn/switch-case-brace` and `prefer-regex-literals`.

**Comment by rdwebdesign** [comment]
Logical operators (`Logicall OR(||)` and `nullish coalescing operator`) are useful in some situations [like this](https://github.com/pi-hole/AdminLTE/blob/master/scripts/pi-hole/js/db_graph.js#L21), but I don't think it should replace all ternary occurrences.

**Comment by yubiuser** [comment]
Force pushed to resolve merge conflicts.

**Review by PromoFaux — APPROVED** [review]

**Pull request merged**
