### PR TITLE
Adding the ability to declare multiple MAC addresses 

### PR DESCRIPTION
**Pull request by s482dcaw**
Adding the ability to declare multiple MAC addresses in DHCP static entries
This is allowed by dnsmasq so the changes are only on the web interface
to allow registering the lines, and presenting them properly

Signed-off-by: s482dcaw <s482dcaw@nameprivate.eu>

**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

`{A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues}`

**How does this PR accomplish the above?:**

`{A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix}`

**What documentation changes (if any) are needed to support this PR?:**

`{A detailed list of any necessary changes}`

> - `{Please delete this quoted section when opening your pull request}`
> - You must follow the template instructions. Failure to do so will result in your issue being closed.
> - Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> - Detail helps us understand an issue quicker, but please ensure it's relevant.

### CODE REVIEW

**Comment by yubiuser** [comment]
Follow-up of https://github.com/pi-hole/AdminLTE/pull/2108

**Comment by s482dcaw** [comment]
The patch also resolves the issue: https://github.com/pi-hole/AdminLTE/issues/1543

**Comment by s482dcaw** [comment]
I have noticed that this is stuck, is there something I need to do to take this forward?

**Comment by yubiuser** [comment]
>  is there something I need to do to take this forward?

Nothing you can do.  None of the devs running Pi-hole as DHCP server had time for reviewing so far. We try our best, but real life is happening too.

Please be patient.

**Comment by PromoFaux** [comment]
I may be able to test this at some point as I have access to a Pi-hole acting as DHCP server - however first the merge conflicts will need to be resolved

**Comment by s482dcaw** [comment]
I have updated my local copy and resynced, but I do not know what you expect now. Shall I submit a new pull request?

**Comment by PromoFaux** [comment]
No longer relevant due to the removal of `php` from the `development` branch in preparation for v6

**Pull request closed without merging**
