### PR TITLE
refactor FTLConfig into class, fix privacy not updating

### LINKED ISSUE #1783: Settings > Privacy does not show updated as expected
### Versions
Pi-hole version is v5.3.1 (Latest: v5.3.1)
AdminLTE version is v5.5 (Latest: v5.5)
FTL version is v5.8 (Latest: v5.8)

### Platform
- OS and version:  Raspbian GNU/Linux 10 (buster) debian
- Platform:  Raspberry Pi

### Expected behavior
I visit the page Settings > Privacy (/admin/settings.php?tab=privacy)
The DNS resolver privacy level is set to Show everything and record everything
I change it to Anonymous mode and press Apply

The page should refresh and show the DNS resolver privacy level is set to Anonymous mode

### Actual behavior / bug

The page refreshes, a blue bar shows saying "Info - The privacy level has been increased" but the DNS resolver privacy level is still Show everything and record everything

When I manually refresh the page, the correct DNS resolver privacy level is showing.

The same happens in reverse.

### Steps to reproduce

As above

## Debug Token

- URL:  https://tricorder.pi-hole.net/am4g9pc59k

### PR DESCRIPTION
**Pull request by lionralfs**
**By submitting this pull request, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

Fixes #1783 

**How does this PR accomplish the above?:**

PR #1131 introduced a way to read the FTL config file. It also added a way to cache the config to avoid unnecessary re-reads (as evident in the PR review).
However, this lead to the config only being read once from disk, not taking into account any possible changes to the file.
This in turn caused bug #1783 where the privacy settings were written to the config file but these lines returned the cached version of the config file:
https://github.com/pi-hole/AdminLTE/blob/50f43bde73d25211ac2c81e9092be67512611d2a/scripts/pi-hole/php/FTL.php#L16-L19

I refactored the function into a class with an update method, so any code that modifies the config also has the opportunity to call `FTLConfig::update()` to reflect the changes.

Alternatively, we could completely remove the caching of the config file, as I'm not sure there is much of a performance gain anyways.

Also, I'm not sure which PHP version you're targeting, because I'm using `private`, which is only available in PHP >= 7.1 if I'm not mistaken.

**What documentation changes (if any) are needed to support this PR?:**

I hope my code comments are good enough for this change, but I'm willing to write additional docs if needed.

### CODE REVIEW

**Comment by PromoFaux** [comment]
>Also, I'm not sure which PHP version you're targeting, because I'm using private, which is only available in PHP >= 7.1 if I'm not mistaken.

I don't remember off the top of my head the version of PHP we currently target, but I know that work that has been happening behind the scenes for 6.0 will either completely remove PHP or limit us to a lower version... I'm a little behind on this, though, so will ping @DL6ER for a response.

**Comment by DL6ER** [comment]
Yes, for v6.0 we're currently embedding [PH7](https://github.com/symisc/PH7) (not to be confused with PHP7!):

> PH7 implements most of the constructs introduced by the **PHP 5.3** release

However, the real goal is ditching PHP altogether moving the web interface to all-static code as this would drastically reduces the potential attack surface. If this can be achieved, I don't know. Things like `<? include("file.php"); ?>` are very handy and avoid code duplication but the latter seems to be acceptable given what the gains of dropping PHP are.

**Comment by lionralfs** [comment]
That sounds awesome! Does this affect my proposed use of `private`? It doesn't seem like you're using `public`/`private`/`static` modifiers anywhere else. In fact, the only other class is here: 
https://github.com/pi-hole/AdminLTE/blob/50f43bde73d25211ac2c81e9092be67512611d2a/scripts/pi-hole/php/database.php#L315-L320

I'm by no means an expert in PHP, so any guidance is appreciated.

**Comment by thebeanieman** [comment]
Hello,

This does not seem to fix https://github.com/pi-hole/AdminLTE/issues/1783 . Exactly the same error happens with Web Interface [v5.12].

Thanks,
David

**Pull request closed without merging**
