### PR TITLE
Have two spaces between indicator and text in Status panel

### LINKED ISSUE #3106: "Status": Small formatting issue
### Versions

- Pi-hole:  v5.18.3
- AdminLTE:  v5.25.2
- FTL:  v5.21

### Platform

- OS and version:  Raspberry Pi OS Lite (64-bit), Bookworm
- Platform:  Raspberry Pi

### Expected behavior

Same number of spaces.

### Actual behavior / bug

After "Load:", "Memory usage:" 2 spaces. 
After "Temp:" 1 space.

### Steps to reproduce

Imo not necessary

### Debug Token

...

### Screenshots

If required...

### Additional context

N/A

### PR DESCRIPTION
**Pull request by yubiuser**
**What does this PR aim to accomplish?:**

Fixes https://github.com/pi-hole/web/issues/3106

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by rdwebdesign** [comment]
Why do we need 2 spaces?

EDIT:

After looking at your changes and the linked issue, they are talking about different things.

You changed the spaces between the icon and the text. The issue was complaining about the number of spaces AFTER the colon.

In v6, the number of spaces after the colon is already 1 in all cases (that's why I said it was already fixed in v6).

I still don't know if we need 2 spaces between the icon and text.

**Comment by yubiuser** [comment]
Maybe personal taste but I think 2 spaces look better than one.

The issue persist in V6. Currently, status and temperature have only 1 space, CPU and memory have 2.

**Comment by rdwebdesign** [comment]
I was editing my previous comment when you posted the new one. They are different spaces.

**Comment by yubiuser** [comment]
Ah I see, your are correct. But there were also different amount of spaces between the icon and the text. The difference might be small, but for me having only 1 space between the thermometer icon and "Temp" (the T stretches to the left) doesn't look so good than having 2. 

Screenshot at 2024-08-12 07-49-03
Screenshot at 2024-08-12 07-48-19

_____

No matter how we decide, but the number of spaces should be consistent

**Review by rdwebdesign — APPROVED** [review]

**Pull request merged**
