### PR TITLE
v5.14.2

### PR DESCRIPTION
**Pull request by PromoFaux**

### CODE REVIEW

**Review by yubiuser — APPROVED** [review]

**Comment by PromoFaux** [comment]
@jojost1 - can you confirm that API calls are working with the latest `dev` please?

**Comment by jojost1** [comment]
@PromoFaux I'm home in a few hours and - if it's still needed then - I can. How do I switch to the dev branch?

**Comment by PromoFaux** [comment]
`pihole checkout web devel` (and then `pihole checkout web master` to go back!)

**Comment by jojost1** [comment]
@PromoFaux I was able to check remotely (with Pi-hole Remote) and it works! 😊

_The only feature that doesn't work in my app is the CPU/RAM/Temp display because of the new web interface (I used to parse the html), but that's a different issue and unrelated to this fix._

**Comment by PromoFaux** [comment]
> The only feature that doesn't work in my app is the CPU/RAM/Temp display

This is something we are unlikely to support over API, btw, as really it's irrelevant information for a DNS server. If I could go back in time, I probably would have argued not to include this information on the dashboard at all :) But that's just me

**Pull request merged**
