### PR TITLE
Add the ability to filter domains by type

### PR DESCRIPTION
**Pull request by rdwebdesign**
### What does this PR aim to accomplish?:

After a recent update, all domains are shown on the same page.

This PR adds the ability to filter domains by type, allowing turn on/off the visibility of:
- Exact whitelists;
- Exact blacklists;
- Regex whitelists;
- Regex blacklists.

### How does this PR accomplish the above?:

Adding a filter and checkboxes to control the filter. 

image

### What documentation changes (if any) are needed to support this PR?:

none.

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
- [x] I have read the above and my PR is ready for review. _Check this box to confirm_

### CODE REVIEW

**Review by yubiuser — COMMENTED** [review]
I deselected all checkboxes, but instead of showing no domains it switched back to show all domains. This is kind of counter-intuitive. Is this the expected behavior?

**Comment by DL6ER** [comment]
I wonder if this makes the page again somewhat more complex to use. This also requires extra amounts of space, if we keep it, could we explore having this in the box-header instead of in a dedicated row?

**Comment by rdwebdesign** [comment]
Answering each question:

> Is this the expected behavior?

Yes.
Actually, the initial behavior was to have all checkboxes deselected, showing everything. If you select something, everything would disappear except the selected one. If you select another, it would be added to the selection.
After testing, I decided to start with all selected, but keep the "show all", if none are selected (I don't see a reason to hide all).

> This also requires extra amounts of space, if we keep it, could we explore having this in the box-header instead of in a dedicated row?

I thought about that and I think is a great idea. I only put the filter with the other controls because I think nobody would like it there.

**Review by yubiuser — COMMENTED** [review]
I like the new position of the checkboxes, it fits in there very well. I would just change the order of "Exact blacklist" and "RegEx whitelist", so both withlist and both blacklist boxes are grouped. This  makes it easier to "restore" the old function to only see whitelist/blacklist entries.

___
> Is this the expected behavior?
>
> Yes.
> After testing, I decided to start with all selected, but keep the "show all", if none are selected (I don't see a reason to hide all).

Sure it makes no sense to deselect all and expect any output - however, I would argue one would expect to see an empty table then.

**Review by yubiuser — APPROVED** [review]

**Pull request merged**
