### PR TITLE
Finalize renaming adlists -> lists

### PR DESCRIPTION
**Pull request by DL6ER**
# What does this implement/fix?

Finish the only partially done renaming `adlists` -> `lists` on the dashboard. This fixes a few broken links such as "Manage lists" on the dashboard as well as the generated links from the Search Lists page to the Groups -> Lists page with enabled list row highlighting

**Related issue or feature (if applicable):** N/A

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

### CODE REVIEW

**Comment by yubiuser** [comment]
I'm not so happy with that change. I know gravity can now contain also allowlists (anti-gravity) and adlists is not the best term anymore. However, a generic 'list' makes it impossible to distinguish gravity from manually managed allow/deny lists.

**Comment by DL6ER** [comment]
Github says:
Screenshot from 2023-10-17 22-24-58

yet on the CLI:
```
$ git merge development-v6 

Auto-merging scripts/pi-hole/js/groups-lists.js
Merge made by the 'ort' strategy.
 scripts/pi-hole/js/gravity.js      | 3 +--
 scripts/pi-hole/js/groups-lists.js | 2 +-
 2 files changed, 2 insertions(+), 3 deletions(-)
```

:thinking:  :man_shrugging:

**Comment by PromoFaux** [comment]
> However, a generic 'list' makes it impossible to distinguish gravity from manually managed allow/deny lists.

Would you mind expanding on this a little? Do you have an alternative suggestion?

**Comment by DL6ER** [comment]
Maybe along the lines of `subscriptions` or `subscribed lists` but they are pretty long phrases. Or we go German and say `Abos` (which means subscriptions)

**Comment by yubiuser** [comment]
In the end it comes down to the difference between `subscibed lists` and `self-curated lists` (and a few different supported syntax on the lists). I think `subscriptions` is a nice term - it can be both "adlist" and "anti-adlists" now. And `domainlist` can stay as it is

**Comment by DL6ER** [comment]
Screenshot from 2023-10-24 19-31-37

This is just too long to be good...

**Comment by PromoFaux** [comment]
Coming back to this... I think `lists` is an adequate descriptor for this, and to be honest I'm failing to see where the confusion would lie. Subscriptions is a change of terminology all together, and would possibly cause even more confusion...

**Review by PromoFaux — DISMISSED** [review]

**Review by NittanySeaLion — COMMENTED** [review]
In groups-lists.lp, line 65, consider changing "List of subscribed lists" to "Subscribed lists"

**Review by PromoFaux — APPROVED** [review]

**Pull request merged**
