### PR TITLE
Update chart.js to 4.4.0

### PR DESCRIPTION
**Pull request by yubiuser**
**What does this PR aim to accomplish?:**

Update chart.js to 4.4.0. Only minor changes were needed to get it working properly.

Migration guide: https://www.chartjs.org/docs/latest/migration/v4-migration.html

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [ ] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Review by DL6ER — DISMISSED** [review]
Screenshot from 2023-10-26 18-05-17

**Comment by DL6ER** [comment]
On other notes: Looking at the screenshot above, it looks like we could really improve the contrast on the doughnut labels, what do you think (this is the `Pi-hole auto` theme)? @yubiuser @rdwebdesign 

Screenshot from 2023-10-26 18-07-47
seems we are using the same gray on `deep-midnight` where it is less of an issue as the background is darker - still not really great

**Comment by yubiuser** [comment]
We could use the same color we use for the box heading

**Comment by yubiuser** [comment]
Good catch. As per migration guide

> Removed fallback to fontColor for the legend text and strikethrough color.

___

Should be fixed now
Screenshot at 2023-10-26 22-21-25

**Review by DL6ER — APPROVED** [review]

**Comment by DL6ER** [comment]
Just for the record: This PR updated Chart.js all the way from [v3.9.1...v4.4.0](https://github.com/chartjs/Chart.js/compare/v3.9.1..v4.4.0)

**Pull request merged**
