### PR TITLE
Remove "Power off" and "Restart System" buttons

### PR DESCRIPTION
**Pull request by rdwebdesign**
### What does this PR aim to accomplish?

This PR removes 2 buttons from the web interface.

### How does this PR accomplish the above?

Removing the buttons and changing the layout to accommodate 4 buttons instead of 6.
Settings_buttons

### Link documentation PRs if any are needed to support this PR:

none 

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Review by yubiuser — CHANGES_REQUESTED** [review]
There is more to delete here. 
`setting.js` has the js code which can be removed as well. 
L362-369 in `settings.php` can go as well.
`savesettings.php` has unused code now as well.

And probably a companion PR for code to remove `pihole -a reboot/poweroff`

**Review by yubiuser — COMMENTED** [review]
Should all the buttons have the same color?

**Comment by rdwebdesign** [comment]
I don't think so, but this can be changed... 

The previous buttons were 3 yellow (I guess the intended meaning was "attention") and 3 red (meaning "Danger").
We removed 2 "dangerous" buttons, but other one is the same.

On the other hand, I'm not sure if we should consider "Flush Logs" more dangerous than the others.

**Comment by yubiuser** [comment]
> On the other hand, I'm not sure if we should consider "Flush Logs" more dangerous than the others.

^This

**Comment by rdwebdesign** [comment]
Quickly reviewing past commits, I noticed this button used "btn-warning" and "btn-primary" (the normal blue button) CSS classes on the past.

I think the color was more a design choice than a functional choice.

Do you think we should change something else? Order of the buttons? Texts?

**Comment by yubiuser** [comment]
Ideal solution: "Flush network table" can be removed, if the network table had a "multi-select" as we have for clients/adlists.... Disable query logging could go to "Privacy". They all should have the same color (orange is fine) or "Restart DNS resolver" should be the only one in red and should stay at the top right.

**Comment by rdwebdesign** [comment]
> Ideal solution: "Flush network table" can be removed, if the network table had a "multi-select" as we have for clients/adlists.... 

This can be done in a future PR.

> Disable query logging could go to "Privacy".

I think we could ADD the same button there (also in another PR), but I don't think we need to move it from this System tab.

**Comment by yubiuser** [comment]
Ok, then move "Restart DNS resolver" to the right and make them all orange or "Restart" red (as you prefer)

**Comment by rdwebdesign** [comment]
The "Restart DNS resolver" is already at the right side. I don't think we need to use different colors.

image

**Comment by yubiuser** [comment]
Ah, it's because you force-pushed, need to pull manually.

**Review by yubiuser — APPROVED** [review]
Approving. But I would like to get more opinions on this change from @pi-hole/web-maintainers

**Comment by rdwebdesign** [comment]
I force pushed to avoid too many (and meaningless) commits.

**Comment by yubiuser** [comment]
Pining @pi-hole/web-maintainers about their opinion to remove reboot/shutdown from the web interface in v6

**Comment by DL6ER** [comment]
They serve no meaningful purpose other than being (part of) a handy system management tool replacement. When we remove them, we should also remove the endpoints from the API and this will allow us to strip the power-management capability we currently manually grant to `pihole-FTL`.

**Comment by yubiuser** [comment]
>  we should also remove the endpoints from the API 

That's why I'm asking ;-)

**Comment by DL6ER** [comment]
Related: https://github.com/pi-hole/FTL/pull/1606

**Comment by yubiuser** [comment]
Superseded by https://github.com/pi-hole/AdminLTE/pull/2664

**Pull request closed without merging**
