### PR TITLE
Resolve merge conflicts development-v6 > devel

### PR DESCRIPTION
**Pull request by yubiuser**
**What does this PR aim to accomplish?:**

Resolve merge conflicts development-v6 > devel

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by yubiuser** [comment]
This PR would add the LCARS-Picard to v6. It has not adaped yet. for cleanness we could keep it in this PR and remove it in `devel` once it was merged. Or the author could adapt/fix(?) it once it's in `devel`

**Comment by PromoFaux** [comment]
We could disable the theme for the time being until such time as it is ready to be adapted? Not 100% sure what would need to be fixed as I've only ever just whatever the default theme is!

paging @MichalSvatos

**Comment by rdwebdesign** [comment]
There was a PR (https://github.com/pi-hole/web/pull/3031) to add the theme to v6, but it was automatically closed due to unresolved merge conflicts.

**Note:**
The also theme needs to be added to FTL repo.
The PR https://github.com/pi-hole/FTL/pull/1971 was also closed with unresolved merge conflicts.

**Comment by yubiuser** [comment]
I removed the LCARS picard theme. It can be re-added anytime.

**Comment by PromoFaux** [comment]
Cool, happy to merge this as-is. @rdwebdesign, if you have the time could you take a look over the two closed PRs for the theme and see if anything needs doing?

**Review by PromoFaux — APPROVED** [review]

**Comment by rdwebdesign** [comment]
@PromoFaux 

There are 2 closed PRs related to the new theme:
- https://github.com/pi-hole/web/pull/3031 (web repo): I think this one will need to be rebased on top of the current `development-v6`. As a suggestion, I think the author should check the theme again, to be sure there is nothing visually broken after the changes we recently merged here.
- https://github.com/pi-hole/FTL/pull/1971 (FTL repo): I also think it just needs a rebase. Then we will need to review it.

**Comment by Xeddius** [comment]
If someone, anyone, can please fix the LCARS Picard theme, I would be forever grateful. It was my favorite and now it's completely missing. It's the most visually appealing theme out of anything available, I updated only to watch my UI look significantly worse all of a sudden with no way to resolve it.

**Comment by MichalSvatos** [comment]
> If someone, anyone, can please fix the LCARS Picard theme, I would be forever grateful. It was my favorite and now it's completely missing. It's the most visually appealing theme out of anything available, I updated only to watch my UI look significantly worse all of a sudden with no way to resolve it.

As I mentioned in the other comment - I'm really sorry 🙁 I'll do my best to fix it soon.
**Thank you for your kind words!** ❤️

**Pull request merged**
