### PR TITLE
dependancy: Fontawesome from 5.15.1 > 6.4.0

### PR DESCRIPTION
**Pull request by AlexLamond**
**What does this PR aim to accomplish?:**

Upgrades the dependancy of Fontawesome from V 5.15.1, to version 6.4.0 - This provides new icons and a new style: 'thin'

**How does this PR accomplish the above?:**

Replaces V5.15.1 of min.all.js with V6.4.0 of min.all.js

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [X] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by yubiuser** [comment]
Thanks for your PR. 

However, your PR is based on a very outdated base branch (>1000 commits behind). If you base the branch on the current development branch you will notice, that some icons were removed from front-awesome and thus break the page. You would need to carefully inspect every page/menu for broken icons.
Additionally, the new file is 270kB larger than the old one without "real" benefit. 

Currently I don't see this getting merged - perhaps we could update once we got v6 in a more advanced state. You'll find the current v6-development branch here: https://github.com/pi-hole/AdminLTE/tree/devel-v6

**Comment by AlexLamond** [comment]
Well that's really odd, I brought my branches up to date 😅

I'll try again with this one, I've another change request I'm working on that needs Fontawesome 6, we can hold off this one for now, but I'll reference this PR once I get that PR in place

**Comment by yubiuser** [comment]
> Well that's really odd, I brought my branches up to date

Almost

Screenshot at 2023-05-04 21-04-24

**Comment by DL6ER** [comment]
> perhaps we could update once we got v6 in a more advanced state. You'll find the current v6-development branch here: https://github.com/pi-hole/AdminLTE/tree/devel-v6

This is already done in v6.0

https://github.com/pi-hole/AdminLTE/blob/8bca7bfa0fd54e3f2ea90c5834b883d46d3c7cdb/style/vendor/font-awesome/js/all.min.js#L2

**Comment by yubiuser** [comment]
Superseded and included in https://github.com/pi-hole/AdminLTE/pull/2603

**Pull request closed without merging**
