### PR TITLE
Use pgrep file instead pidof. Fix HTML rendering issue.

### PR DESCRIPTION
**Pull request by m2meier**
**By submitting this pull request, I confirm the following:**

- [X] I have read and understood the [contributors guide], as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license]
- [X] I have squashed any insignificant commits. (`git rebase`)
- [X] I have Signed Off all commits. (`git commit --signoff`)
---

**What does this PR aim to accomplish?**
Use `pgrep` instead of `pidof` to detect the `pihole-FTL` process id. `pidof` is not necessarily available and/or in the PATH on certain systems, e.g. CentOS. 

Further down I fixed a small issue in the HTML rendering of the temperature indication.

**How does this PR accomplish the above?**
n/a

**What documentation changes (if any) are needed to support this PR?**
n/a

### CODE REVIEW

**Comment by yubiuser** [comment]
Thanks for the PR. How about doing the same as Pi-hole does on the cli - checking for `/run/pihole-FTL.pid`? See [here](https://github.com/pi-hole/pi-hole/pull/4103) for the discussion why `pgrep` was omitted (as fallback) to check if FTL is running.

**Comment by m2meier** [comment]
Thank you for the suggestion. I couldn't find an explanation in the mentioned comment, why do or don't use `pgrep`. IMHO it is not unlikely that file system access is restricted for a PHP application. Nevertheless: You asked for "The Full Monty". Here it is... ;-)

**Comment by yubiuser** [comment]
Woowo. That's a lot of effort.

The reason was mainly, that users should be warned/informed that something is wrong if the PID file is missing.

**Review by PromoFaux — DISMISSED** [review]
Thanks for the submission

**Comment by PromoFaux** [comment]
> not unlikely that file system access is restricted for a PHP application

This is actually a good point. I've just tested it working OK on my dev system, but tbh I probably shouldn't trust because I do everything there as `root`

Can someone test this please on a normal raspberry pi with standard permissions etc set? (I don't currently have a Pi in operation? @pi-hole/debug

**Comment by DL6ER** [comment]
Merging this PR will throw the already 60% working v6.0 branch a lot backwards because of creating *a whole lot* of merge conflicts. All this has already been rewritten to work without PHP as this information is now provided by the Pi-hole API in new `system` callbacks.

**Comment by PromoFaux** [comment]
Actually, yes that is a very fair point - I guess almost akin to decorating your living room just before demolishing your house.

@m2meier Can we take this back to the first commit, please?

**Comment by m2meier** [comment]
@PromoFaux Do whatever you want. @yubiuser asked for a solution using the PID file. If my additional work breaks your release... throw it away.

**Pull request closed without merging**
