### PR TITLE
Revert "Move some duplicated code to utils.js"

### PR DESCRIPTION
**Pull request by XhmikosR**
This reverts commit 3957e9eef1382a852e5be2ba0202c57175279f23.

Signed-off-by: XhmikosR <xhmikosr@gmail.com>

**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

`data` can be null after calling `localStorage.getItem` so we need the error checking in each call anywa. We could revisit later.

### CODE REVIEW

**Comment by DL6ER** [comment]
How does reverting the reduction of code duplication fix things? We should port the existing (?) error handling correctly into the one piece of code where everything got united.

**Comment by XhmikosR** [comment]
It does fix the issue because now there's a check for null after each `localStorage.getItem` call.

We should merge it and revisit if it's worth moving this later.

**Comment by XhmikosR** [comment]
From a quick look, it's not worth abstracting this. But again, it's something we should think better later.

**Comment by DL6ER** [comment]
But there *is* a check for this:

https://github.com/pi-hole/AdminLTE/pull/1391/files#diff-52047ac562bcace5fa0d94122736ceacL160-L162

Maybe I cannot see the wood for the trees. I don't think we should undo this quickly, we should have a solution now.

**Comment by XhmikosR** [comment]
The check is not enough, because the utils function returns null itself.

**Comment by XhmikosR** [comment]
`stateLoadCallback` needs a null check always. `stateSaveCallback` could be abstracted but again is just one line so it doesn't gain us anything IMHO.

We can revisit this later, after evaluating if it's worth it.

**Pull request closed without merging**
