### PR TITLE
Improving the menu

### PR DESCRIPTION
**Pull request by rdwebdesign**
**By submitting this pull request, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

This PR tries to improve the menu.

**How does this PR accomplish the above?:**

Minor visual changes to the menu:
- replace some icons;
- 2 new custom icons added;
- "Query List" renamed to "Search Adlists".

<details>
<summary>Screenshot</summary>

new_icon_suggestions_small

</details>

**What documentation changes (if any) are needed to support this PR?:**
none (_maybe replace a few screenshots_)

### CODE REVIEW

**Comment by yubiuser** [comment]
Before:

Bildschirmfoto zu 2022-03-22 10-15-49

After:

Bildschirmfoto zu 2022-03-22 10-16-46

Bildschirmfoto zu 2022-03-22 10-16-53

Bildschirmfoto zu 2022-03-22 10-17-10

Bildschirmfoto zu 2022-03-22 10-17-24

**Review by yubiuser — COMMENTED** [review]
I'm fine with most changes. However, I don't like the user-clock icon. It's the only one with an animation and doesn't really fit within the others. How about `fa-timer` or `hourglass-clock`?

Would it be possible to have the custom svgs as files and not directly in the source code?

**Comment by rdwebdesign** [comment]
It was a typo (I have no idea how this got deleted).
Fixed.

**Review by yubiuser — APPROVED** [review]
Looks better now ;-)
Bildschirmfoto zu 2022-03-23 00-48-58

**Pull request merged**
