### PR TITLE
Remove temperature settings forgotten after #3139

### PR DESCRIPTION
**Pull request by rdwebdesign**
### What does this PR aim to accomplish?

Please see title.

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Review by yubiuser — APPROVED** [review]
Part of the FTL stuff could still be removed

**Comment by rdwebdesign** [comment]
Do you mean to remove these options from FTL or do you mean remove from "All Settings" page?

If you remove from FTL, they will be automatically removed from "All Settings" page (this page is dynamic).

**Comment by yubiuser** [comment]
From FTL... Without removing the things necessary for PADD.

**Comment by rdwebdesign** [comment]
If we remove these options from FTL / API, how will PADD users change the temperature unit?

**Review by DL6ER — APPROVED** [review]

**Pull request merged**
