### PR TITLE
solving build problem - test footer changes

### PR DESCRIPTION
**Pull request by mledecky1091**

### CODE REVIEW

**Comment by Mcat12** [comment]
@mledecky1091 are you @miro1091?

**Comment by miro1091** [comment]
> @mledecky1091 are you @miro1091?

yes, I have created another github account (to make another fork from your repo) to determine problem with building app, maybe it was not the best solution, but i had to try it :) ...but now, it's taking too long for making CI test

**Comment by miro1091** [comment]
It's difficult to say, why that build CI crashes if there is some code, but on localhost everything have been working well

**Comment by Mcat12** [comment]
Have you tried examining why the CI fails? You have to have the code compile, match the formatter, and pass the tests. This can all be done without pushing commits.

**Comment by Mcat12** [comment]
Develop changes on one branch, and have one PR.

**Pull request closed without merging**
