### PR TITLE
Tweak deleting message

### PR DESCRIPTION
**Pull request by yubiuser**
**What does this PR aim to accomplish?:**

Be more specific what we delete from one of the tables. The current wording could be misinterpreted. See: https://discourse.pi-hole.net/t/database-locked-one-symptom-deleting-one-entry-in-pi-hole-diagnosis-triggers-deleetion-of-1616-invisible-messages-which-fails/60388/7?u=yubiuser

I changed the code to show meaningful information to the user when there is some (e.g. name of the group which is deleted) or only print a generic statement if not ("Deleting messag(s)").

In case of an error, the corresponding `id` is always shown.

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by saint-lascivious** [comment]
From [this](https://www.reddit.com/r/pihole/comments/10fq20i/dismissed_messages_notification_query/) Reddit thread, where this ended up confusing me for a different reason, and then giving me more questions:

> What's the direct value of communicating this ID to the user? There's no way I would have even remembered the value if I didn't screenshot it and go looking for it consciously, and it's not clear what if anything one can do with that piece of information.
>
> To be clear, with the proposed change, say I deleted multiple messages in a single session. Does that mean there would be N popups with "Deleted message/group/adlist/etc with ID: $FOO", where N == number of messages dismissed (incidentally the popup stacking when there's multiple messages can be kind of off-putting and prevent user interaction while you wait for the notification stack to disappear)?
>
> A single notification displaying the number of messages deleted in total perhaps seems a little cleaner, but that's said in the context of not knowing what displaying the ID is intended to achieve.
>

Edit: If there's a TL;DR here it's basically "even when it's clear what the value is, it's not clear _why_ it is".

**Comment by yubiuser** [comment]
> To be clear, with the proposed change, say I deleted multiple messages in a single session. Does that mean there would be N popups with "Deleted message/group/adlist/etc with ID: $FOO", where N == number of messages dismissed (incidentally the popup stacking when there's multiple messages can be kind of off-putting and prevent user interaction while you wait for the notification stack to disappear)?

If you delete multiple messages/clients/groups/.. there should be only one popup WIth "Deleting messages with ID: 1,2,3,4"

___

But I get your point. For the users it does not make sense to have this information. It does not translate to anything meaningful for them. I'll see if we can improve this or simplay stating "Deleting XXX...". In case of an error I would keep the ID. I think we can have more meaningful output for groups/clients/adlists, but maybe not "messages".... Let's see...

**Comment by jfb-pihole** [comment]
I am in favor of leaving the ID's in the message.  This may be useful in diagnosing user problems in the future, and won't confuse any users.  I would rather have it and rarely use it than rarely need it and not have it.

"Deleting messages with ID: 160, 167, 168" would be my preferred output.

**Comment by saint-lascivious** [comment]
> I am in favor of leaving the ID's in the message.  This may be useful in diagnosing user problems in the future
> 
> I would rather have it and rarely use it than rarely need it and not have it.
> 

There's clearly an argument that it's useful information to have for potential debugging purposes, but I don't think that necessarily translates into being useful information to have in a confirmation notification that's user facing.

A (potentially quite large) list of IDs that _might_ possibly be useful in the future is debug/log info.

**Comment by yubiuser** [comment]
I changed the code to show meaningful information to the user when there is some (e.g. name of the group which is deleted) or only print a generic statement if not ("Deleting messag(s)").

In case of an error, `id` is always shown.

Please try it with `pihole checkout web tweak/messages`

**Comment by yubiuser** [comment]
Peek 2023-01-20 17-03

**Comment by saint-lascivious** [comment]
Looks fine over here.

Thanks yubi, for both your work, and being open to change. It's appreciated.

**Review by PromoFaux — APPROVED** [review]

**Pull request merged**
