### PR TITLE
Added test page for ad block confirmation

### PR DESCRIPTION
**Pull request by gitkatsi**
Signed-off-by: gitkatsi <30192727+gitkatsi@users.noreply.github.com@gmail.com>

## Thank you for your contribution to the Pi-hole Community!

Please read the comments below to help us consider your Pull Request.

We are all volunteers and completing the process outlined will help us review your commits quicker.

**Please make sure you**

 1. Base your code and PRs against the repositories developmental branch.
 2. [Sign Off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits as we enforce the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
 3. [Sign](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all your commits as they must have verified signatures
 4. File a pull request for any change that requires changes to [our documentation](https://docs.pi-hole.net/) at our [documentation repo](https://github.com/pi-hole/docs) 

---

**What does this PR aim to accomplish?:**

Create a test page so a user can easily identify if pi is properly set up. Some times routers advertise themselves as dns servers and ignore user settings. This way a user can test each device if it is respecting his settings. 

**How does this PR accomplish the above?:**

5 common for me blocked domains are used in order to see if they fail to replay to a GET request via javascripts fetch.

testpagejpg

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x ] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by rdwebdesign** [comment]
You need to fix some things:

- DCO: You need to remove `<` and `>` from your e-mail, on your local git config.
- PHP-CS-Fixer: [fix format](https://github.com/pi-hole/AdminLTE/actions/runs/3422320384/jobs/5699586523)
- Tests / Node: [fix format](https://github.com/pi-hole/AdminLTE/actions/runs/3422320373/jobs/5699586556)
- editorconfig-checker: [fix whitespace](https://github.com/pi-hole/AdminLTE/actions/runs/3422320371/jobs/5699586421)

**Comment by jfb-pihole** [comment]
I am not in favor of this change.  Adding arbitrary domains to a test page does not add any value, and the functionality already exists.

The network tab will show all the network clients and indicate if they are using Pi-hole or not.

Using the following command will show the DNS servers being provided by the DHCP server:

`pihole-FTL dhcp-discover`

Additionally, a simple nslookup from a client for a known blocked domain will confirm whether the client is using Pi-hole, and whether Pi-hole blocks the domain for that client.

**Comment by gitkatsi** [comment]
> I am not in favor of this change. Adding arbitrary domains to a test page does not add any value, and the functionality already exists.
> 
> The network tab will show all the network clients and indicate if they are using Pi-hole or not.
> 
> Using the following command will show the DNS servers being provided by the DHCP server:
> 
> `pihole-FTL dhcp-discover`
> 
> Additionally, a simple nslookup from a client for a known blocked domain will confirm whether the client is using Pi-hole, and whether Pi-hole blocks the domain for that client.

I seem to have missed the functionality. Can you please guide me to the coresponding page? 
Domains were selected with the following criteria.
1.  It is in my top 5 list. 
2.  They are on the default blacklist

If pihole is used as a dhcp server. if not it will show only queries from the router itself

`pihole-FTL dhcp-discover` will show info for pi itself not every device on the network. Routers sometimes advertise themselves as DNS servers on wifi (especially on android devices), so instead of respecting the DHCP settings they resolve with ISP's DNS.  

nsolookup will indeed show that in a conventional pc.  in mobile devices it requires extra software. 

This test page was inspired by the fact that even though in my case pi-hole managed to block ads to certain devices i still had ads on mobile devices. The only way to test those devices was to open  games and push the "watch video button for x gold coins", so i could test that my setup was working or not. 

I'll be out of town for a few days so it will take me a while to fix failing test.

**Comment by jfb-pihole** [comment]
Go to the web admin GUI > Tools > Network.  All visible network clients are listed, and there is a column "uses Pi-hole".  There is a MAC ID associator in the Hardware Address column to help a user figure out which device matches a MAC ID.

> pihole-FTL dhcp-discover will show info for pi itself not every device on the network

I have not seen a DHCP server that passes different information to clients based on whether they are on WiFi or Ethernet.  That is why we run the DHCP-discover command in our debug log - to find out what the DHCP server is distributing to all clients.

> Domains were selected with the following criteria.
>
>    It is in my top 5 list.
>    They are on the default blacklist

Not everybody runs the default blocklist.

In our debug log, to test blocking, we pick a random domain from gravity, then test that domain.  That way, we know the domain we are testing should actually be blocked.

> The only way to test those devices was to open games

The network tab would show you that the device was not using Pi-hole, if in fact it was not.

We added the network tab specifically to help users identify clients that were bypassing Pi-hole.

**Pull request closed without merging**
