### PR TITLE
Fix queries Clear Filters button

### PR DESCRIPTION
**Pull request by XhmikosR**
Now it should look like the rest of the buttons

Signed-off-by: XhmikosR <xhmikosr@gmail.com>

**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

### CODE REVIEW

**Comment by PromoFaux** [comment]
image

The button is now visible by default, which is interesting, especially as the `hidden="true"` is still set.

When applying a filter and then clicking the button it disappears as you would expect, but when reloading the page it comes back.

**Comment by XhmikosR** [comment]
I don't see how this can can be related to this patch, though :/

**Comment by PromoFaux** [comment]
Yeah, not sure, just commenting what I observed when checking out the branch :) Full cache reload between branches, too/

**Comment by XhmikosR** [comment]
The exact same button classes are used everywhere else:

```
C:\Users\xmr\Desktop\AdminLTE>git grep -rna "id=\"resetButton\""
dns_records.php:84:                <button type="button" id="resetButton" hidden="true" class="btn btn-default btn-sm text-red">Clear Filters</button>
groups-adlists.php:68:                <button type="button" id="resetButton" hidden="true" class="btn btn-default btn-sm text-red">Reset sorting</button>
groups-clients.php:69:                <button type="button" id="resetButton" hidden="true" class="btn btn-default btn-sm text-red">Reset sorting</button>
groups-domains.php:130:                <button type="button" id="resetButton" hidden="true" class="btn btn-default btn-sm text-red">Reset sorting</button>
groups.php:66:                <button type="button" id="resetButton" hidden="true" class="btn btn-default btn-sm text-red">Reset sorting</button>
queries.php:150:            <button type="button" id="resetButton" hidden="true" class="btn btn-default btn-sm text-red">Clear Filters</button>
```

**Comment by XhmikosR** [comment]
Let's leave this until we figure out the root cause.

**Comment by XhmikosR** [comment]
I confirmed the issue, although I have to say it doesn't make sense to me. I will try to fix it later by setting `display: none` or a class if we have one, and then it should be the same.

It's weird because it seems that only this button has this issue...

**Comment by XhmikosR** [comment]
@PromoFaux can you give it another go? BTW more of the reset buttons where showing on devel. This should take care of it.

**Comment by XhmikosR** [comment]
So, apparently Bootstrap 3.x had https://getbootstrap.com/docs/3.4/css/#helper-classes-show-hide

I'll try to remove `d-none` later and make use of those. But probably in another PR.

Even I don't remember the 3.x utils... 🙁

**Pull request merged**
