### PR TITLE
Tweak the Update Gravity output

### PR DESCRIPTION
**Pull request by rdwebdesign**
### What does this PR aim to accomplish?

This PR is intended to show the progress of the new parseList function introduced by https://github.com/pi-hole/FTL/pull/1559 and https://github.com/pi-hole/pi-hole/pull/5275.

The new `pihole-FTL gravity parseList` command starts every message (including error messages) with `\r`, to allow overwriting lines on the command line output.

The problem is: this brakes the web interface output and no output is shown for this command.

Replacing the initial `\r` allows the correct output.

### How does this PR accomplish the above?

Kepping the original `str_replace` and adding a second one, to replace any remaining `\r` with `'<------'`.

#### Note:
Use all 3 branches when testing: [FTL](https://github.com/pi-hole/FTL/pull/1559), [core](https://github.com/pi-hole/pi-hole/pull/5275) and web.

### Link documentation PRs if any are needed to support this PR:

none

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by yubiuser** [comment]
I tried it and with this PR I can see the progress counting. However I fail to see a single occurrence of `<------`

Is this expected?

**Comment by rdwebdesign** [comment]
Yes.

The `<------` string is used only internally and it is replaced.

**Comment by yubiuser** [comment]
Ah I see... it's the code right below. You search for the position in the line string and remove everything you don't want.

**Comment by rdwebdesign** [comment]
The logic is:

`gravity.sh` output is used both on the console and the web interface.

On the console, it uses a _carriage return_ followed by an escape code (`ESC+[K`) to "go back to the start of the line and clear from the cursor to the end of the line". This is used to allow "overprinting" lines, on the same place (similar to PADD).

This escape sequence is sent to PHP/javascript. PHP replace it with `<------`. If the string appears on the middle of the line, PHP strips the text before the `<------`.

The text is sent to javascript with `<------`. The java script code removes it and removes the last printed line, causing the same "overprint" effect.

**Comment by yubiuser** [comment]
Thanks. Maybe you could adjust the code comments a bit, because the part replacing `${OVER}` was removed but is used as explanation in the code.

**Comment by rdwebdesign** [comment]
I didn't remove the `${OVER}` part. I expanded, but I think I could improve the comments.

The `$OVER` sequence can be written in different forms:
- FTL uses `\r\x1b[K`;
- PHP uses `\r\e[K`;
- Shell is using the character, but [github is not able to show it](https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/COL_TABLE#L49). The same happened with the previous PHP code (the character was not shown on github or some text editors). My second commit fixed this.

I will try to rewrite this comment to allow a better understanding.

**Review by yubiuser — APPROVED** [review]
Thanks for the explanation. My main issue was that I did not know that `\r\e[K` and `\r[K` are the same thing.

**Comment by rdwebdesign** [comment]
Yeah,

`\e` = `\x1b` = ESC (ASCII code = 27)

**Comment by rdwebdesign** [comment]
Show the on the web interface the progress count from the new FTL `gravity_parseList()` function.

**Pull request merged**
