### PR TITLE
simple ldap authentication mode

### PR DESCRIPTION
**Pull request by cyberb**
**By submitting this pull request, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

Allows to enable LDAP for user authentication.
Sample config:
```
LDAP_AUTH=true
LDAP_SERVER=ldap://localhost
LDAP_BIND_DN="cn=%s,ou=users,dc=syncloud,dc=org"
```

**How does this PR accomplish the above?:**

Adds ldap auth code and introduces a switch.

**What documentation changes (if any) are needed to support this PR?:**

No

### CODE REVIEW

**Comment by PromoFaux** [comment]
I currently have no way to test this, however, going back to some earlier conversations (or rather, snippets):

On [Jan 8th](https://github.com/pi-hole/pi-hole/issues/3975#issuecomment-757036246) you asked:
> What would be the best place to implement it right now php or c?

And, like some kind of mind reader, I actually already answered that question for you [back in November 2019](https://github.com/pi-hole/web/pull/400#issuecomment-558837856) :wink

The `new/http` branch of `FTL` and `new/FTL_is_my_new_home` branch of this repo are where we're concentrating on any new features for the interface, currently. 

The only things going into the existing implementation are bug fixes and security patches (and/or very small, easily portable changes - but we try not to)

**Comment by cyberb** [comment]
Is new/http released?

**Comment by PromoFaux** [comment]
no

**Comment by cyberb** [comment]
Ok, I can do c but after it is released.

**Comment by PromoFaux** [comment]
Of course, it goes without saying that there are no guarantees it would be accepted when the time comes - just in case there is any false sense of hope relayed (unintentionally) by myself

**Comment by cyberb** [comment]
@PromoFaux could you tell me what is the current source for UI as I cannot seem to understand is it still php (looks like AdminLTE is being actively developed) or FTL (again new/http is still not merged)?

**Pull request closed without merging**
