### PR TITLE
Add padding to apple fav icon and set background to black

### LINKED ISSUE #1958: iOS icon has black background and no padding
### Versions

Pi-hole version is v5.6 (Latest: v5.6)
AdminLTE version is v5.8 (Latest: v5.8)
FTL version is v5.11 (Latest: v5.11)

### Platform

- OS and version:  Rasbian Buster

- Platform:  Pi

### Expected behavior

White background for iOS Home Screen icon with some padding around graphic

### Actual behavior / bug

Black logo background, graphic goes to the edges

### Steps to reproduce

Add to home screen from Safari

### Screenshots

8BABCB6F-C185-413E-B63B-8368B8F7EC01

### Additional context

Would you be open to a PR with a revised set of favicons generated from your SVG using https://realfavicongenerator.net ?

### PR DESCRIPTION
**Pull request by yubiuser**
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

Currently, the `apple-touch-icon` has a transparent background. But adding `pi.hole` to the homescreen on iOS devices will turn this transparent background into black.  The icon has no padding so it appears unusually large compared to other icons. 
This PR adds a black background by default and some padding.

Fixes https://github.com/pi-hole/AdminLTE/issues/1958

For discussion.

### CODE REVIEW

**Comment by XhmikosR** [comment]
The new icon is not transparent anymore, so this patch does not only change the padding.

EDIT: BTW we should probably get rid of the IE-specific icons later.

**Comment by rdwebdesign** [comment]
If the icon is used only for iOS, I think a background color should be used. 

Apple recommends to "_Keep the background simple and avoid transparency_" (at least for app icons).
https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/

**Review by DL6ER — APPROVED** [review]
From #1958:

IMG_0589

**Comment by XhmikosR** [comment]
The apple-touch-icon.png is NOT used only on iOS. It's at least used by Firefox on Android too:

Screenshot_20211224-144840_Firefox

I don't really care care about it, just want to be clear about where it's used and that this PR also changed the background color and not only padding.

**Comment by rdwebdesign** [comment]
How the other icons looks like on Firefox Android? Are they transparent or have a background color?

**Pull request merged**
