### PR TITLE
Update teleporter.php to Pretty JSON Output

### PR DESCRIPTION
**Pull request by draik**
**By submitting this pull request, I confirm the following:** 
`{please fill any appropriate checkboxes, e.g: [X]}`
`{Please ensure that your pull request is for the 'devel' branch!}`

- [ X ] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [ X ] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [ X ] I have tested my proposed changes.
- [ X ] I am willing to help maintain this change if there are issues with it later.
- [ X ] I give this submission freely and claim no ownership.
- [ X ] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ X ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [ X ] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**
`{A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues}`

This will change the JSON output to be on multiple lines, instead of one single line (pretty output)

**How does this PR accomplish the above?:**
`{A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix}`

json_encode has the JSON_PRETTY_PRINT built-in, allowing for the clean/pretty output in the JSON files.

**What documentation changes (if any) are needed to support this PR?:**
`{A detailed list of any necessary changes}`

No further documentation needed for json_encode in PHP

### CODE REVIEW

**Comment by draik** [comment]
Fixed missing signoff for DCO

**Comment by dschaper** [comment]
Why is this needed?

**Comment by draik** [comment]
This isn't a requirement, but would output the JSON contents in easily readable format, instead of one long line to sort through.

**Comment by dschaper** [comment]
The output should be packed in a tarball for machine reading. When would the file need to be read/modified by a human?

**Comment by draik** [comment]
This was a feature request for sharing purposes, but could pick and choose once imported to enable/disable as one chooses.

**Comment by dschaper** [comment]
I only see potential issues with importing so I'm going to say no, but others can approve if they think it's of value.

**Comment by draik** [comment]
If it's going to create issues, then it shouldn't be part of production. Thanks for looking this over. Closing this PR.

**Pull request closed without merging**
