### PR TITLE
Add interface information

### PR DESCRIPTION
**Pull request by DL6ER**
# What does this implement/fix?

This PR implements a Discourse feature request. The particular implementation is up for discussion and possible further improvements therewhile.

Needs https://github.com/pi-hole/FTL/pull/2009 (branch [`tweak/api_network_info`](https://github.com/pi-hole/FTL/commits/tweak/api_network_info)) to work.

----

**Related issue or feature (if applicable):** https://discourse.pi-hole.net/t/list-ip-v4-and-v6-address-in-web-interface/70981/11

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

### CODE REVIEW

**Comment by DL6ER** [comment]
Screen Shot 2024-07-15 at 07 37 23

And an altogether new page which lists all interfaces, expanding interfaces by default which are connected to a default gateway (IPv4 and/or IPv6):

Screen Shot 2024-07-15 at 07 33 40

**Review by yubiuser — CHANGES_REQUESTED** [review]
Both FF and chrome error on this PR, interestingly with different things to complain about.
Screenshot at 2024-07-17 22-58-33
Screenshot at 2024-07-17 22-58-11

**Review by yubiuser — CHANGES_REQUESTED** [review]
The issue is fixed with the latest commits. 
But the appearance is broken for midnight and high contrast dark theme. For deep-midnight the hover effect is to bright.

**Comment by rdwebdesign** [comment]
> For deep-midnight the hover effect is to bright

At the moment, I'm not able to test the branch (this week is really busy) so I didn't see the issue, but looking at the code and the new CSS rules ([style/vendor/bstreeview.min.css](https://github.com/pi-hole/web/pull/3076/files#diff-054f3687976098adc67b229baf4539462bc3252ff8f8cdbd06ea09273dd29b09)), I think the "too bright" issue is happening because the new elements use the same color for every theme:
```css
.bstreeview .list-group-item:hover{background-color:#dee2e6}
```

Adding a new color to `default-darker.css`, with `.bstreeview .list-group-item:hover {background-color: <new color>}` should fix it.

When I have the time I will try to add a few CSS rules to fix this elements in the dark themes.

**Pull request closed without merging**
