### PR TITLE
Friendly language

### PR DESCRIPTION
**Pull request by isdampe**
Implements support for #311

### CODE REVIEW

**Comment by PromoFaux** [comment]
Thanks @isdampe for the submission. Could I be a pain and ask you to re-base your branch on the `development` branch? Looks like you may have based on `master`, as there are a few merge commits in this PR.

Also, whilst we don't explicitly state it on this repository, please review the status of the [DCO bot](https://github.com/pi-hole/pi-hole/pull/2859/checks?check_run_id=177170212) and action accordingly to make it happy!  We have a [guide here](https://docs.pi-hole.net/guides/github/how-to-signoff/) if you need pointers on that. 

Cheers!

**Comment by isdampe** [comment]
My bad - yeah I can do that when I get a few minutes. Thanks!

**Comment by isdampe** [comment]
I finished this last week, but I'm unable to test on `development` because there seems to be a bug on the branch with the fake data. The page continuously reloads / refreshes in a loop. I'll push the updates once this is fixed.

**Comment by Mcat12** [comment]
I cannot reproduce the refreshing you describe. Can you open an issue with more details?

**Comment by isdampe** [comment]
Closing this and send an amended PR from a fixed branch

**Pull request closed without merging**
