### PR TITLE
Switch from fontawesome webfonts to SVG + JS

### PR DESCRIPTION
**Pull request by notriddle**
**By submitting this pull request, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

There are several problems with icon fonts. My biggest problem is that I see a box with `F104` in it where there ought to be a picture, because I have web fonts disabled (for the same reason I use Pi-hole; most of the time, web fonts are a waste of time and they're in the critical path for rendering the page). Other people disable web fonts because they're dyslexic and want to have custom fonts used all the time, which is a far more important reason to make sure your site is usable without web fonts.

Web fonts are also [anti-aliased as fonts](https://css-tricks.com/icon-fonts-vs-svg/), which can look ugly. Basically, using fonts for icons results in a bunch of stuff not really treating them correctly.

> https://discourse.pi-hole.net/t/use-svg-for-icons-instead-of-font/40166
>
> https://speakerdeck.com/ninjanails/death-to-icon-fonts

**How does this PR accomplish the above?:**

It uses Font Awesome's SVG + JS configuration. Since the Pi-hole dashboard already requires JavaScript to work at all, and it's very close to being a total drop-in replacement for the older CSS + Web Font setup, it seemed like the best choice with the least impact on the rest of the code. It's also supported by FontAwesome, and they have other nice features built into it.

The biggest downside is that it's a non-async JavaScript. If I had made it async, or loaded the script at the bottom of the page instead of the top, you'd have gotten a bit of jank when the script finished loading. The way to avoid both jank and avoid forcing the icons to load before the page becomes visible by inlining the icons or by using the plain SVG sprite, but that would have been a more invasive change to the AdminLTE code. At least this way, it only loads one file (a giant JavaScript file) instead of two (the CSS and the Web Font).

Before:

image

After:

image

**What documentation changes (if any) are needed to support this PR?:**

This should have no user-visible changes, except making things work in configurations where they used to be broken.

### CODE REVIEW

**Comment by dschaper** [comment]
Thank you for the submission and the detailed explanation why it's needed. I'm not much of a JS guy so I can't attest to the code itself, but I like the concept.

**Comment by PromoFaux** [comment]
@XhmikosR Can you take a look over this, please? This seems in your wheelhouse.

**Comment by XhmikosR** [comment]
I'm not sold on the benefits of this, personally. I still use fonts and I have no issue with this approach.

That being said, this change should be made upstream too so that it reaches a bigger audience and more people benefit. Last time I checked, AdminLTE 3.x used the CSS. But if this is accepted upstream, one more reason to go with it here too.

Assuming all instances are changed, and someone tests this, it's your call, at the end. I don't have a lot of time to test this myself.

**Comment by XhmikosR** [comment]
Also, the less JS, the better. I haven't measured this at all nor how much it affects the page size, but JS needs to be parsed and executed.

Just my 2 cents :)

**Comment by dschaper** [comment]
I agree with XhmikosR that this should be a change at the upstream level. But in this case, we are the upstream since we've forked. 

The vue node package is moving to SVG+JS and has noted no bad effects. https://www.npmjs.com/package/@fortawesome/vue-fontawesome#learn-about-our-new-svg-implementation

**Comment by notriddle** [comment]
> Last time I checked, AdminLTE 3.x used the CSS. But if this is accepted upstream, one more reason to go with it here too.

They added support for it already.

https://github.com/ColorlibHQ/AdminLTE/pull/2920

**Review by DL6ER — APPROVED** [review]
Upstream AdminLTE already has this in `master` as well as `v3.1.0-rc`. As there were no other objections, we can merge this. Thanks a lot for your contribution!

**Pull request merged**
