### PR TITLE
Provide fake username on login form

### LINKED ISSUE #2418: Chrome Password no longer autopopulating
### Versions

- Pi-hole:  5.13
- AdminLTE:  5.18.2
- FTL:  5.16

### Platform

- OS and version:  Bebian Buster

- Platform:  Raspberry Pi

Chrome 107.0.5304.88 (64 Bit)

### Expected behavior

When I go to pihole web interface, password autopopates or is selectable. worked in prior versions of pihole. 

### Actual behavior / bug

no longer populates password. Did notice the site chagned so clared out of chrome and logged in and added, but does not popuplate. 

### Steps to reproduce

load pihole web ui
password does not prompt
have to go to chrome setttings password to find password
to copy and paste, to log in. 

image

### PR DESCRIPTION
**Pull request by yubiuser**
**What does this PR aim to accomplish?:**

When a password is set for the web interface, we use `autocomplete="current-password"` on the password login form to allow browsers and password managers to auto-fill the input field. This works well with e.g. Firefox, but fails on Chrome (see https://github.com/pi-hole/AdminLTE/issues/2418).
To fix this, we add a hidden input field providing a fake username (`pi.hole`).

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
- [x] I have read the above and my PR is ready for review. _Check this box to confirm_

### CODE REVIEW

**Comment by yubiuser** [comment]
Note to self: get rid of Chrome's autofill CSS modifications of the input box

**Comment by rdwebdesign** [comment]
This PR will solve the issue, but I think this is a browser bug introduced recently.

To be sure, I tested using the current browser version and 2 different Pi-hole versions (docker image latest and 2022.02) and the password is **not** saved in both cases.

Without your PR, I was able to save the password on both browsers using the normal procedure, but I needed to type an username:
- access the page, type the password and click on "Log in" button;
- the browser will show a pop up to save the password;
- **type any username** and click "save";
- the password will be saved.

**Comment by yubiuser** [comment]
Do you think I should not proceed with this PR as this is an external "bug" (and we could simply wait until they fix it)? Maybe they don't see this as a bug, but as a feature and won't fix it ever?

**Comment by yubiuser** [comment]
Ready for review. 

I adjusted the CSS to overwrite the auto-fill style on Chrome browsers.

**Review by rdwebdesign — APPROVED** [review]

**Pull request merged**
