### PR TITLE
Improve wording: Percentage blocked domains

### PR DESCRIPTION
**Pull request by heis2201**
Improve wording: "Percent blocked" --> "Percentage blocked"

**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [ ] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [ ] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [ ] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

### CODE REVIEW

**Comment by heis2201** [comment]
I have no clue how to sign a commit after pushing it here on github.

**Comment by yubiuser** [comment]
https://docs.pi-hole.net/guides/github/how-to-signoff/

**Comment by heis2201** [comment]
> https://docs.pi-hole.net/guides/github/how-to-signoff/

That means one cannot change a file here in Github - or at least only people familiar with git, which I am not. So closing...

**Comment by yubiuser** [comment]
You can `amend` a sign-off and push (or force-push) the commit again.

**Comment by heis2201** [comment]
> You can `amend` a sign-off and push (or force-push) the commit again.

If you know what you are doing, you can do a lot.

**Comment by yubiuser** [comment]
It's the last section of the how-to-guide. You can copy paste the command.

I admit, learning git is hard - I only mastered enough to be able to push some PRs here. Still need to look-up some commands every time I haven't worked with git for a while

**Comment by dschaper** [comment]
You can also do a lot when you ask for help.

**Review by PromoFaux — APPROVED** [review]

**Pull request merged**
