### PR TITLE
Sidebar and nav-tab-custom: additional CSS for focus state

### LINKED ISSUE #1843: No visual indicators of side menu items keyboard focus
### Versions
- Pi-hole:  v5.3.1
- AdminLTE:  v5.5
- FTL:  v5.8.1

### Platform
- OS and version:  Ubuntu 20.04.2 LTS
- Platform:  (GNU/Linux 5.4.106-1-pve x86_64)

### Expected behavior
When navigating the admin app with the keyboard, the side menus items should be highlighted, when they are focused

### Actual behavior / bug
There is no visual indication whatsoever that a menu item is focused

### Steps to reproduce
1. Open the admin panel (you might have to login, but it is already reproducable bevore)
2. Press tab an your keyboard
3. Notice how there is no focus indicator on the side menus items

### PR DESCRIPTION
**Pull request by rdwebdesign**
Signed-off-by: rdwebdesign <github@rdwebdesign.com.br>

**By submitting this pull request, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

Fixes #1843, improving accessibility for sidebar and nav-tabs.

**How does this PR accomplish the above?:**

Added CSS for `:focus` state, into every theme: _default-light.css_, _default-dark.css_, and _default-darker.css_.
Each theme has been modified accordingly.

**What documentation changes (if any) are needed to support this PR?:**

none

### CODE REVIEW

**Comment by yubiuser** [comment]
Thanks for fixing the issue.
However, I have two remarks:
1) On the light setting, I see a blue line when focusing with the mouse, but a grey line with keyboard
2) On the midnight theme I don't see a visual indication at all

I think I would prefer to have the line blue in all cases.


Bildschirmfoto zu 2021-11-01 13-02-49
Bildschirmfoto zu 2021-11-01 13-03-14

**Comment by rdwebdesign** [comment]
@yubiuser 

Wait. 
`focus` is different than `hover`.

### Light Theme (default-light.css):
Before the modifications we had a blue border on "hover", but there was no different visual on focus.
Now, we still have a blue border on "hover", but the text is white and I added a border on focus too. 
The focus border color is different than the hover, but I can change that.
light

### Midnight Theme (default-dark.css):
Before we had white text and darker background on "hover", but no visual effects on focus.
Now, hover is the same, but on focus the text is white and I added a border.
midnight_theme

### Deep Midnight Theme (default-darker.css ):
Before we had white text and darker background on "hover", but no visual effects on focus.
Now, hover is the same, but on focus the text is white (the difference is small).
deep-midnight


**Note:** images showing the sidebar and nav-tabs using only the keyboard.


Any suggestions?

**Comment by yubiuser** [comment]
Thanks for the nice screenshots.
From my usability point of view hover and focus are even here: when I use the mouse, I hover and one click opens the resp. menu. If I use the keyboard, I focus and one "return" opens the menu. Have I overlooked something?

Therefore hover and focus can/should be the same I think - or rephrasing: I don't see a need to distinguish them. I like the border esp. on the left side menu and would add it to all of the themes.

P.S. Add it to the new theme as well ;-)

**Comment by rdwebdesign** [comment]
Focus and Hover styles can be different or not. It's a design choice. 
In this case, I agree that we don't need to distinguish between then. I can change that.

>  ... I like the border esp. on the left side menu and would add it to all of the themes.

What do you mean?
The deep-midnight theme doesn't have it. 
Actually, there is a border-color (on hover CSS), but there is no border for the element. 
I thought that was somebody else's design choice, made before and I don't want to change it without more information.

>P.S. Add it to the new theme as well

The new theme already has focus effects for the sidebar menu.

**Comment by rdwebdesign** [comment]
Just to add to our conversation...

From the usability point of view we have many states:
- Normal state (nothing is happening);
- Hover state (ex: mouse pointer is over a button or link);
- Active state (ex: you are clicking a button or a link);
- Focus state (ex: you used <kbd>TAB</kbd> key to move the focus)

The focus state will happen using the mouse too (_interactive elements only: links, buttons, input elements, etc._):
- if you selected an element with a click, the element gets the focus. Then, when you remove the mouse pointer after that, the focus will stay on the element until another action changes the focus again.

We don't normally need focus state, but some people with disabilities cannot use the mouse and need a visual cue to know where the focus is.

In the sidebar, using the mouse, you usually don't see the focus because you click and the focus disappears immediately when the new page loads, but using the keyboard you can navigate using <kbd>TAB</kbd> and select/fire the desired action using <kbd>Return</kbd> or <kbd>ENTER</kbd>.

**Comment by yubiuser** [comment]
> The deep-midnight theme doesn't have it.
Actually, there is a border-color (on hover CSS), but there is no border for the element.
I thought that was somebody else's design choice, made before and I don't want to change it without more information.

I think it would benefit from one. But askIn the sidebar, using the mouse, you usually don't see the focus because you click and the focus disappears immediately when the new page loads.

I noticed this as well: it also happens if you click on the sidebar and keep the button pressed. It's most obvious on the light theme as (so far) it has different colors for hovering and focussing. ing @DL6ER who created the theme initially. 
___

> We don't normally need focus state, but some people with disabilities cannot use the mouse and need a visual cue to know where the focus is.

That's why I would add a "border for the element" to make the focus even clearer.

**Comment by rdwebdesign** [comment]
@yubiuser 

I changed the CSS for the sidebar.
Now using the mouse or the keyboard you will see the same effect.

Each theme will change the text color, background-color and left-border (with the same color on both states) for `:hover` and `:focus` ;

**Review by yubiuser — APPROVED** [review]

**Pull request merged**
