### PR TITLE
Add stickler-CI to test yaml and mkdown files

### PR DESCRIPTION
**Pull request by yubiuser**
This adds stickler-CI workflow to lint markdown and yaml files.

Uses https://pypi.org/project/yamllint/ and https://github.com/remarkjs/remark-lint internally

### CODE REVIEW

**Comment by yubiuser** [comment]
This repo needs to be enabled on `https://stickler-ci.com/`

**Comment by PromoFaux** [comment]
Did we not already remove stickler at some point in the past?

**Comment by yubiuser** [comment]
Searching for `stickler` PRs did not yield any results.

**Comment by rdwebdesign** [comment]
I think it is enabled now.

**Comment by rdwebdesign** [comment]
Do you think we need to ignore "vendor" files?

```yml
files:
  ignore:
    - '/scripts/vendor/*'
```

**Comment by yubiuser** [comment]
It's not complaining now...but maybe does in the future? Shouldn't we report broken styling back to them if errors occur instead of ignoring the files?

**Comment by rdwebdesign** [comment]
I don't think we should do this for external code.

We can report upstream style issues if we found them, but I don't think this should block/delay a PR.

**Comment by yubiuser** [comment]
Converted to draft until we figured out why files are not ignored and if we can fix this.

**Comment by yubiuser** [comment]
The issue is fixed, files are ignored now as they should.
Reason was the leading `/` in the paths which is removed now.
This was tested on https://github.com/pi-hole/AdminLTE/pull/2239

**Review by rdwebdesign — APPROVED** [review]

**Pull request merged**
