### PR TITLE
Replace references of `devel` with `development` in prep for change of branch name

### PR DESCRIPTION
**Pull request by PromoFaux**
### **What does this PR aim to accomplish?:**

Counterpart to https://github.com/pi-hole/pi-hole/pull/5748, should we go along the path of renaming `devel` to `development` (we probably should)

These PRs should be either the last things merged into `development-v6` or the first things merged into `development` after the merge of `v6`->`development`

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
- [x] I have read the above and my PR is ready for review. _Check this box to confirm_

### CODE REVIEW

**Comment by PromoFaux** [comment]
Branch protections etc would need fixing on the repo

**Review by DL6ER — DISMISSED** [review]

**Review by rdwebdesign — DISMISSED** [review]

**Review by yubiuser — DISMISSED** [review]
I'm not sure about dependabot. This might need to go to master

**Comment by PromoFaux** [comment]
Ah yes, maybe. We can do that afterwards

**Review by DL6ER — APPROVED** [review]
Re-approving because nothing has really happened

**Pull request merged**
