### PR TITLE
Adding <thead> where missing

### LINKED ISSUE #1378: Tables: make sure we use a `thead`
There are some tables that don't have a `thead`. We should make sure every table has a `thead` assuming it's needed, instead of adding a `tr` in `tbody` that behaves like a `thead`.

### PR DESCRIPTION
**Pull request by paul-man**
Signed-off-by: Paul Mannarino <paul.mannarino@gmail.com>

**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

Resolve #1378 

**How does this PR accomplish the above?:**

Utilize <thead>for header rows in all tables

**What documentation changes (if any) are needed to support this PR?:**

None

### CODE REVIEW

**Comment by XhmikosR** [comment]
Thanks for the PR!

Do note that in some cases `thead` is added via JS. Did you double check we don't add it twice? Ideally, we should reduce what we add via JS and do it in HTML when possible.

**Comment by paul-man** [comment]
@XhmikosR I actually didn't didn't double check the HTML that was formed, I just went to each page to see things were rendered properly. I'll go ahead and do that!

**Comment by PromoFaux** [comment]
> I'll go ahead and do that!

Hey, did you get a chance to double check things?

**Comment by DL6ER** [comment]
Closing due to inactivity. Feel free to re-open the PR once they are resolved.

**Pull request closed without merging**
