### PR TITLE
Compress images

### PR DESCRIPTION
**Pull request by GChuf**
**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

- [x ] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x ] I have made only one major change in my proposed changes.
- [  ] I have commented my proposed changes within the code.
- [x ] I have tested my proposed changes.
- [x ] I am willing to help maintain this change if there are issues with it later.
- [x ] I give this submission freely and claim no ownership.
- [x ] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x ] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

I hope the title is pretty self explainatory. The main change here is the donate.gif file, which is now a smaller png file. The gif file also was not cached in my browser, unlike other images.

I also compressed some other files while still trying to keep the appropriate quality for their sizes. In other words, the difference in quality is not noticeable.

### CODE REVIEW

**Comment by dschaper** [comment]
This changed the modes for all the images to `755` which will get a "No" from me. Can you fix that?

**Comment by XhmikosR** [comment]
Yeah, I don't like the mode changes and the lack of info about the tools used. I need to be able to reproduce the results.

**Comment by GChuf** [comment]
My bad - the modes are now `644.`
As for compression, I forgot to mention that I used png indexing.
I've tried some CLI programs like mogrify, imagick, ... but the best results I've had were using this website:
https://compresspng.com/
Still trying to figure out which tool is being used here, and how.

For the background jpg, I reduced the JPG quality using photoshop.

**Comment by XhmikosR** [comment]
Thanks for the info. TBH I went lossless last time I compressed the images, minus 8-bit for the PNG favicons after I generated them.

I will play with it and submit a patch in the next days, because I found more savings opportunities with open source tools, which I personally prefer.

**Comment by XhmikosR** [comment]
> For the background jpg, I reduced the JPG quality using photoshop

What quality did you choose, though? I'm getting quite better results here even with 90% quality (which is an overkill obviously).

**Comment by GChuf** [comment]
@XhmikosR I did see that 'someone' was losslessly optimising images, but I thought that for things like favicons (16x16 and 32x32) it would be nice to add some lossy compression as well.
By _minus 8 bit_ for favicons you mean without alpha?

I also prefer open source, but like I said, I wasn't able to generate good indexed pngs myself. 

The JPG image - photoshop doesn't give you the percentage option when choosing quality, instead it offers you a scale from 1 to 12. I believe I chose 8 or 9.

**Review by DL6ER — CHANGES_REQUESTED** [review]
`img/boxed-bg.jpg` cannot be removed without breaking boxed layout

**Comment by GChuf** [comment]
> 
> 
> `img/boxed-bg.jpg` cannot be removed without breaking boxed layout

The files are compressed, not removed.

**Comment by XhmikosR** [comment]
I still whatever improvements that apply to upstream should be submitted there first...

**Comment by GChuf** [comment]
@XhmikosR fixed

**Comment by PromoFaux** [comment]
All pull requests must be submitted against `devel` - I don't think @XhmikosR meant to change the base branch to `master`...

**Comment by GChuf** [comment]
> All pull requests must be submitted against `devel` - I don't think @XhmikosR meant to change the base branch to `master`...

I dont know what upstream is referring to, then. Im happy to make the appropriate changes if this gets merged.

**Comment by dschaper** [comment]
Who would be the upstream for our own images?

**Comment by DL6ER** [comment]
Closing due to inactivity. Feel free to reopen if you want to continue working on this.

**Comment by GChuf** [comment]
@DL6ER whatever work I wanted to do, is finished ... I can reopen if someone will merge.
I don't know what the actual problem was - XhmikosR first commented that they want to play around with it to get more savings, then they said something about "upstream" and that changes should be submitted there first . . .

Again, if you guys wanna merge, I'm reopening it whenever you want.

**Pull request closed without merging**
