### PR TITLE
Update jquery.confirm to 2.7.0

### PR DESCRIPTION
**Pull request by yubiuser**
**What does this PR aim to accomplish?:**

Updates ` jquery.confirm` to latest version `2.7.0`
We use `jquery.confirm` from https://github.com/myclabs/jquery.confirm to generate the `jquery` confirm modals. The repo is unmaintained since 2017 with a last release from 2016 (2.7.0). There are no maintained, updated forks I could find.
What I could find is https://github.com/craftpip/jquery-confirm which implements the same idea. However, their last release is from 2019 qith >180 open issues - which indicates development was abondened as well so I did not switch to this plugin.

Despite being old, I still think it's doing it's job and we should upgrade to the latest version.

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
- [x] I have read the above and my PR is ready for review. _Check this box to confirm_

### CODE REVIEW

**Comment by yubiuser** [comment]
P.S. I could not find a minified version > 2.3.1 so I minified myself.

**Comment by PromoFaux** [comment]
I've not looked at what we use `jquery.confirm` for, but just putting this out there:

https://sweetalert2.github.io/

**Comment by yubiuser** [comment]
We use it for confirming the dangerous actions in "Settings/System"

**Comment by yubiuser** [comment]
I'll give it a try :)

**Comment by yubiuser** [comment]
Before I start to replace `jquery.confirm`: this has a size of 3kB, whereas `sweetalert` (minified) has 63kB. Do we care or don't we (because Pi-hole should run locally anyway)?

**Comment by rdwebdesign** [comment]
We need to weight the pros/cons here.

The current plugin is old and not maintained. I think it should be replaced.
On the other hand, the new file is bigger (not a very big file, but 20x the old one).

Do we have another (and smaller) alternative?

**Comment by yubiuser** [comment]
> The current plugin is old and not maintained. 

Maybe it's just "done" - in the sense of: it does what it does and does not need more features.

**Review by DL6ER — APPROVED** [review]

**Comment by DL6ER** [comment]
I approve as in: I agree to use the latest (available) version. I will not merge yet as there may still be a search for a smaller plugin ongoing. However, as the last comment is more than two weeks old, this search may just have ended without any result and - in that case - I'm happy with merging. It's less than 3 KB in the end. That shouldn't be a problem in any kind of slow network I can assume these days. Even not in metered ones. Every image viewed on the Internet consumed *orders* of magnitude more bandwidth.

**Comment by rdwebdesign** [comment]
I think we should use `jquery.confirm 2.7.0`.
All alternatives I saw are bigger and will need a lot more changes.

**Pull request merged**
