### PR TITLE
Tweak (vendor) folder structure

### PR DESCRIPTION
**Pull request by yubiuser**
**What does this PR aim to accomplish?:**

Unifiy the vendor file structure. 
The web interface includes some `vendor` files like scripts and styles. The structure has grown organically and was placed in `/scripts/vendor` and `/style/vendor`. However, this distinction was not stringent as e.g. `/style/vendor/bootstrap` also contained some `js` files. 
This PR unifies the structure by placing all vendor files in `/vendor` with appropriate sub-directories. There is no distinction between `style` and `scripts` anymore.
This has also the advantage that updates of those files usually come as bundled archives which can now easily placed in one folder and one does not search for different file locations.

Within `/scripts` there was only one sub-directory left `/scripts/pi-hole`. I moved all files from `/scripts/pi-hole/XXX` to `/scripts/XXX` as it seems unnecessary to keep the `pi-hole` sub-dir. 

I also added the forgotten dependencies to `package.json` to be included into the dependabot updates. Except `js-warn` which does not exist on `npm`.

**No functional changes!!**

The new structure looks like

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Review by DL6ER — APPROVED** [review]
I tried the branch and it seems everything is still working as it should. No 404 or any other errors have shown up. This will make our lives a bit harder if we need to trace something via `git blame` but this isn't a show stopper.

**Comment by rdwebdesign** [comment]
> This will make our lives a bit harder if we need to trace something via git blame but this isn't a show stopper.

Do you think it would be better if the `pi-hole` directory is not changed?

**Comment by DL6ER** [comment]
I don't think we ever really *needed* `git blame` as we do not "blame" users. But sometimes it is nice to use it for finding out what the correlated motivation of the corresponding commit was. It is still possible, but more work after this change.

**Comment by rdwebdesign** [comment]
> It is still possible, but more work after this change.

If it happens, we can "blame" yubiuser... :grin:

**Comment by yubiuser** [comment]
I'll take the risk 😅

**Pull request merged**
