### PR TITLE
Remove useless css, fix chart overflowing, improve the visual and load scripts faster. 

### PR DESCRIPTION
**Pull request by Gontier-Julien**
**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

It remove useless `background-color` that isn't needed, it fix the chart overflowing on mobiles devices, it make the interface look a bit more modern not much but improve the overall visual and make some script load asynchronously for faster loads time.

**How does this PR accomplish the above?:**

- Removing of  `backround-color` on the `.box-header`,
- Fix the chat overflowing on mobile device by removing `height: 250px;` on `.chart-legend`,
- Fix the gray bar on the side of the interface by removing ` border-left-color: #272c30;` on `.sidebar-menu > li.active > a`,
- Improvement of the loading of the scripts by adding  `async` to them on the `.header.php` file.

**What documentation changes (if any) are needed to support this PR?:**

None

### CODE REVIEW

**Comment by dschaper** [comment]
Thanks for the submission!

Can you break the changes in to a few PRs that address each change separately?

**Comment by Gontier-Julien** [comment]
Yeah no problem I will do it tomorrow when i come back from work.
I'll just gonna need to see how to do this i'm pretty new a the github thing ^^'

**Comment by dschaper** [comment]
No problem, if you need any tips or help then just let us know. We all were new to git and GitHub when we started.

**Comment by Gontier-Julien** [comment]
Thank you very much ^^
Also i'm working to make more scripts load asynchronously but need a lot more testing and will require a beta for all of this, juste to be sure not to break anything ^^

**Pull request closed without merging**
