### PR TITLE
Fix mass-deletion of sessions on the settings -> API page

### PR DESCRIPTION
**Pull request by DL6ER**
# What does this implement/fix?

See title and related Discourse topic.

**Related issue or feature (if applicable):** N/A

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

### CODE REVIEW

**Comment by PromoFaux** [comment]
Something not quite right here. Sometimes it deletes all but one session. Seems a bit random as to which session gets left over.

notquite

**Comment by yubiuser** [comment]
Maybe it's an issue with `ownSessionID`

**Comment by rdwebdesign** [comment]
I wasn't able to replicate the "all but one" issue using different browsers (Chrome, Firefox and Edge) on the same machine.

You used different windows from the same browser (using incognito mode). I'm not sure if this could be related to the issue you are seeing. We probably need more tests.

**Comment by DL6ER** [comment]
The issue was the concurrency of the deletions. This is fixed by the latest commit

**Review by yubiuser — COMMENTED** [review]
We have 3 functions now with very similar names: `deleteSessions()`, `delSessions(ids)` and `delSession(id,...)`. The first one does not do much on it's own, maybe the single line `  var ids = [$(this).attr("data-del-id")];` can be part of `delSessions()`?

**Review by yubiuser — APPROVED** [review]

**Pull request merged**
