### PR TITLE
Edited message for DHCP

### PR DESCRIPTION
**Pull request by bigbadmonster17**
## Thank you for your contribution to the Pi-hole Community!

Please read the comments below to help us consider your Pull Request.

We are all volunteers and completing the process outlined will help us review your commits quicker.

**Please make sure you**

 1. Base your code and PRs against the repositories developmental branch.
 2. [Sign Off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits as we enforce the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
 3. [Sign](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all your commits as they must have verified signatures
 4. File a pull request for any change that requires changes to [our documentation](https://docs.pi-hole.net/) at our [documentation repo](https://github.com/pi-hole/docs) 

---

This PR simply appends a message in settings.php to inform users to run 'sudo service pihole-FTL restart' on their pihole if their devices are not issued the static IP address they have set.

https://github.com/pi-hole/pi-hole/issues/3063

A message is at the end of the page shown at the bottom 

**Link documentation PRs if any are needed to support this PR:**

I only added a simple text, so I don't think documentation is necessary.

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [X ] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by yubiuser** [comment]
Thanks for your contribution. Please rebase on and target the `devel` branch.

Pinging @DL6ER as he implemented this part of the code: was there a reason why `FTL` is not restarted (it's not, I just checked by adding a static assignment) when the static assignments were changed?

**Comment by DL6ER** [comment]
Looking at `git blame` I wrote this six years ago, I guess it's okay that I don't really remember my thoughts back then. In the end it may simply be like that because we wanted to avoid a dozen restarts if you are just starting to fill this list.

**Comment by yubiuser** [comment]
Fair point.

___

@bigbadmonster17 we enforce DCO, please add your signature https://docs.pi-hole.net/guides/github/how-to-signoff/

**Comment by rdwebdesign** [comment]
@bigbadmonster17

You need to fix a few issues:

- You need to target your PR on **`devel`** branch (it is currently targeting `master`). You can edit this clicking on the "Edit" button, near the PR title.

- Your commit needs to be **DCO Signed** (this is different than _GPG signature_), please read https://docs.pi-hole.net/guides/github/how-to-signoff/ and add your signature to the commit.

**Comment by bigbadmonster17** [comment]
Hi! Thanks for showing me how to target the devel branch (i was just googling on how i could do that when the message came up)

I have two issues:
1. I edited the comment to include the DCO Signoff with my student email which is causing an issue with the bot checking DCOs
2. After targeting the devel branch the package-lock.json has conflicts of which I'm not too sure how to resolve

**Pull request closed without merging**
