### PR TITLE
Remove duplicate DNSSEC explanation

### PR DESCRIPTION
**Pull request by vmstan**
**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

Remove duplicate DNSSEC explanation

**How does this PR accomplish the above?:**

Deletes duplicated HTML code

**What documentation changes (if any) are needed to support this PR?:**

None

### CODE REVIEW

**Comment by dschaper** [comment]
Can you follow the directions on https://github.com/pi-hole/AdminLTE/pull/1494/checks?check_run_id=878035149 and update the commits please?

**Comment by vmstan** [comment]
> Can you follow the directions on https://github.com/pi-hole/AdminLTE/pull/1494/checks?check_run_id=878035149 and update the commits please?

Sorry about that, my first time submitting to someone else's repo.

**Comment by dschaper** [comment]
No problem, meant as a friendly reminder but I see that it reads kind of abrasive.

**Comment by vmstan** [comment]
Nope. All good!

**Review by DL6ER — APPROVED** [review]

**Pull request merged**
