### PR TITLE
Regenerate package-lock.json

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by Mcat12** [comment]
Please give some reasoning for this PR in the PR description. Right now it's not clear to me why this is being done.

**Comment by XhmikosR** [comment]
I actually have 3 pushed 3 patches here.

Initially I just regenerated package-lock.json so that we get everything fresh, similarly to #516. But I found a few deps that shouldn't be listed in package.json. I could probably split the patches if needed.

**Comment by Mcat12** [comment]
#516 also didn't have any description. If you want to upgrade dependencies, then go through Dependabot. If you want to remove dependencies, then please make that explicit in the PR description, along with why they should be removed.

**Comment by XhmikosR** [comment]
This isn't updating the dependencies. And dependabot has issues with flattening the deps tree.

The commit messages are explicit enough already. I guess I could split the last 2 patches to a separate PR.

**Comment by Mcat12** [comment]
Ok, so if this isn't updating dependencies and isn't about removing dependencies (assuming the last two commits are unrelated to the original PR), then what is it about? You say "I just regenerated package-lock.json so that we get everything fresh", but what does "fresh" mean? What is the functional change that you are proposing? Are you trying to make the dependency tree smaller? Is there a new lock file format that this upgrades us to? Communication is more important than you seem to realize.

**Comment by XhmikosR** [comment]
Right, no point in bothering any more with this.

**Pull request closed without merging**
