### PR TITLE
Add vendor listings to DHCP lease table

### PR DESCRIPTION
**Pull request by smithjacobj**
## Thank you for your contribution to the Pi-hole Community!

Please read the comments below to help us consider your Pull Request.

We are all volunteers and completing the process outlined will help us review your commits quicker.

**Please make sure you**

 1. Base your code and PRs against the repositories developmental branch.
 2. [Sign Off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits as we enforce the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
 3. [Sign](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all your commits as they must have verified signatures
 4. File a pull request for any change that requires changes to [our documentation](https://docs.pi-hole.net/) at our [documentation repo](https://github.com/pi-hole/docs) 

---

**What does this PR aim to accomplish?:**

Not everything has a hostname; this adds a column containing the vendor to the DHCP leases table to help determine what is what when looking through DHCP leases.

image

**How does this PR accomplish the above?:**

This change uses the existing `macvendor` SQLite table that FTL obtains from the Wireshark repo.

**Link documentation PRs if any are needed to support this PR:**

N/A?

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by yubiuser** [comment]
Thanks for the PR. There are some tests failing.
Besides this, we are currently in the transition to the new `v6` web interface (at `development-v6`). We do not plan to have any `v5` release (other than hotfixes). 
Therefore I would put this PR on hold until we merged `development-v6` > `devel` and ask you to rebase once this has been done.

**Comment by smithjacobj** [comment]
> Thanks for the PR. There are some tests failing. Besides this, we are currently in the transition to the new `v6` web interface (at `development-v6`). We do not plan to have any `v5` release (other than hotfixes). Therefore I would put this PR on hold until we merged `development-v6` > `devel` and ask you to rebase once this has been done.

Yeah I was editing this on my home server through a poorly-configured vim - fixing those lint issues. For v6, should I avoid trying to merge into `devel-v6`? I assume that's feature-locked at the moment?

**Comment by yubiuser** [comment]
>  I assume that's feature-locked at the moment?

Yes. We are still trying to implement (more or less) everything we had with v5 and fix the biggest issues. 

> For v6, should I avoid trying to merge into devel-v6?

You can already rebase on `´devel-v6` but after the merge into `devel` we will set this as target branch.

You'll notice, we try to get rid of `php` but will use `pihole-FTL's` `lua`capabilities.

**Comment by smithjacobj** [comment]
@yubiuser I hate to ask here but couldn't find an appropriate location, even in Discourse - is there documentation on the new API paradigm? Looking at devel-v6 it's hard to determine where the endpoints the Javascript AJAX calls are. I tried looking at FTL as well and wasn't able to tell.

**Comment by DL6ER** [comment]
@smithjacobj The idea is that FTL ships the documentation for its API on its won instead of hosting it online. This has the benefit that different branches will always have an up-to-date documentation as the CI precisely checks if all endpoints are documented, if the documentation contains an endpoint which doesn't even exist, if the endpoints have the exact structure as written in the documentation, if the examples in the documentation follow this exact structure, ...

For now, you can see this documentation where the v6.0 FTL code lives, in the future it will also be uploaded to a less hidden place for someone wanting to checkout the docs before installing FTL or for those wanting to read the `development` documentation without changing their local Pi-hole's branch. Plus a simple `git diff` (or even online on Github) will always show you the exact changes that happened.

https://ftl.pi-hole.net/new/http/docs

This documentation is always automatically updated after each successful CI testing of FTL.

PS: The logo and favicon are missing is an artifact of the current location of the docs. I didn't want to compile them into FTL. When using the self-hosted docs on your Pi-hole, the images offered by the web interface are used and you can see them.

**Comment by smithjacobj** [comment]
@DL6ER thanks, I was looking at the wrong FTL branch. It looks like I should be looking at [new/http](/pi-hole/FTL/tree/new/http) instead of [development](/pi-hole/FTL/tree/development)?

**Comment by DL6ER** [comment]
Yes, sorry. It should be `development-v6` by now

**Comment by PromoFaux** [comment]
No longer relevant due to the removal of `php` from the `development` branch in preparation for v6

**Pull request closed without merging**
