### PR TITLE
Update chartjs to v2.9.3

### LINKED ISSUE #1345: Update Chart.js to the latest version
I initially attempted to do it in #1115, but https://github.com/pi-hole/AdminLTE/pull/1115#issuecomment-627561372:

>This changes the animation for the charts.
>
> **devel**
> ezgif-1-4aa28875e195
>
> **your branch**
> ezgif-1-1e4070ceb80d

Being that Chart.js has quite a few improvements so far, including performance ones, we should update it.

Unfortunately, from a quick look I had, I couldn't make the loading animation the same. I tried `animation.duration = 0` and even `animation: false`.

### PR DESCRIPTION
**Pull request by XhmikosR**
**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

Fixes #1345.

### CODE REVIEW

**Review by DL6ER — APPROVED** [review]

**Comment by XhmikosR** [comment]
@DL6ER Are you OK with the changes in the axes? It seems to show more values now.

**Comment by DL6ER** [comment]
Yes, that's fine. I checked it does automatically adapt when there are too many labels
Screenshot from 2020-06-04 13-37-43

**Comment by XhmikosR** [comment]
OK, if you like it. Because this is what I get on my WSL instance which doesn't have a lot of requests

image

**Comment by DL6ER** [comment]
This seems to be the standard behavior for the updated Chart.js. We do not mess with axis ticks anywhere.

**Comment by XhmikosR** [comment]
Ok, so we are merging?

**Comment by DL6ER** [comment]
Yes, I am waiting for the last test to pass. Feel free to overwrite it if it gets stale, however.

**Pull request merged**
