### PR TITLE
Added CustomDNS API

### PR DESCRIPTION
**Pull request by andyloree**
Signed-off-by: Andrew Loree <andy@andyloree.com>

**By submitting this pull request, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**
To add custom (local) DNS to the existing API and it's "auth" (token) support.  This will allow for better integration for other services to modify internal DNS records.

**How does this PR accomplish the above?:**
Taking relevant switch code from customdns.php and adding another elsif branch to api.php

**What documentation changes (if any) are needed to support this PR?:**
- The additional elsif for new parameter "customdns" to the api.php

### CODE REVIEW

**Comment by daledude** [comment]
Can this please be reviewed. I can really use this capability.

**Review by PromoFaux — CHANGES_REQUESTED** [review]
Looks good, I think, though not tested yet. The rest of the file uses tabs, not spaces - picky, I know, but can you please replace your spaces with tabs so that it fits the rest of the file?

Thanks

**Comment by DL6ER** [comment]
Thanks, I think we're close to get this in. DCO complains that you forgot to sign-off your last commit. You can find more details about this here: https://github.com/pi-hole/AdminLTE/runs/1401218961

**Comment by DL6ER** [comment]
We're working on Pi-hole v6.0 which will sunset the PHP API altogether. There will be an interface to manage the custom DNS settings through a predictable REST interface. This will make a lot of things easier and more reliable.

I hope you will understand this. We hope to get a beta period of v6.0 available sometime this year but note that this isn't a promise!

**Pull request closed without merging**
