### PR TITLE
Require auth for recentBlocked function

### PR DESCRIPTION
**Pull request by aidantwoods**
**By submitting this pull request, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

Currently, when querying the `/admin/api.php?recentBlocked` endpoint without being logged into the Pi-hole admin dashboard, the most recently blocked domain name is returned. My assumption is that this is likely an oversight and is not intentional (based on other detailed information being redacted until logged in); if this assumption is false then please feel free to close this PR. I could not find any part of the (logged out) user interface which relied on this functionality (though admittedly I am a relatively new user of Pi-hole).

This PR aims to ensure that detailed information is not unintentionally available by adding an authentication requirement to the mentioned function.

**How does this PR accomplish the above?:**

This PR provides the same authentication check as used on other endpoints in the same file to the `recentBlocked` function.

**What documentation changes (if any) are needed to support this PR?:**

Under the assumption that this information isn't intentionally being made available, I don't believe any documentation update is necessary (bug fix).

### CODE REVIEW

**Comment by dschaper** [comment]
Thanks, I don't think it's exposed intentionally.

**Comment by DL6ER** [comment]
I think this API method is used by `pihole -c`. Chronometer may (or not) use authentication.

**Comment by PromoFaux** [comment]
I guess we could modify chronometer to grab the API key from the settings file?

**Comment by dschaper** [comment]
https://github.com/pi-hole/PADD/blob/master/padd.sh#L174

Uses `/dev/tcp/localhost/4711` to ask FTL for "recentBlocked".

**Comment by dschaper** [comment]
And `chronometer` uses

https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/chronometer.sh#L391

`recent_blocked=$(pihole-FTL recentBlocked)`

**Comment by dschaper** [comment]
Well, let's try!

Screenshot 2020-12-05 134830

Screenshot 2020-12-05 135004

Screenshot 2020-12-05 134638
Screenshot 2020-12-05 134601

**Review by PromoFaux — APPROVED** [review]
So, I've dug back through the history of this file, and the file it stemmed from, right back to the creation of the `recentBlocked` key... I can't see anything that specifically mentions that it is to exist as an unauthed request, so I guess it was overlooked :)

Seems like a sensible thing to add auth to it

**Pull request merged**
