### PR TITLE
Update chart.js to v2.9.3 and moment.js to v2.24

### PR DESCRIPTION
**Pull request by XhmikosR**
Also, switch to the plain chart.js build since their bundle included moment.js, thus include moment before chart.

**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [ ] I have tested my proposed changes.
- [ ] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**This is untested**

The chartjs bundle had moment.js bundled. This patch switches to the normal dist file and includes moment.js separately.

### CODE REVIEW

**Comment by DL6ER** [comment]
This changes the animation for the charts.

**devel**
ezgif-1-4aa28875e195

**your branch**
ezgif-1-1e4070ceb80d

**Comment by XhmikosR** [comment]
Hmm, I'll change the changelog, some defaults might have changed.

**Comment by XhmikosR** [comment]
@DL6ER can you try again please? I downgraded to the same chart.js version, but kept the plain build so that we don't include moment.js 2x.

**Comment by DL6ER** [comment]
Else than my comment, everything seems to work.

However, why did you remove the conditional inclusion of `moment.js`? It is needed by only a small subset of pages and doesn't need to be loaded everywhere.

Furthermore, how does the update of `moment.js` work? You removed the bundle and added a new file only saying:
> ```
> /*!
> * Chart.js v2.9.3
> * https://www.chartjs.org
> * (c) 2019 Chart.js Contributors
> * Released under the MIT License
> */
> ```

There is no mentioning about a contained `moment.js`. This is very unfortunate.

**Comment by XhmikosR** [comment]
The previous chart.js bundle build included moment.js already. So you had it in all pages already.

https://www.chartjs.org/docs/latest/getting-started/installation.html#bundled-build

But we still included moment.js individually. This makes sure we don't load moment.js twice.

**Comment by XhmikosR** [comment]
So, wait does the issue still happen with my latest push?

**Comment by DL6ER** [comment]
No. I'm just wondering that you removed
-  `scripts/vendor/Chart.bundle.min.js`
-  `scripts/vendor/moment.min.js`
and added
-  `scripts/vendor/Chart.min.js`

Nothing is suggesting any more that `moment` is bundled into `Chart`.

If this is still the case, shouldn't the updated file be called `Chart.bundle` as well? This should also remove the adding/removing as the files seem identical:
Screenshot at 2020-05-12 22-14-23

**Comment by XhmikosR** [comment]
I didn't remove moment.js. It's there, minified.

This patch is using the plan chart.js without moment.js, which we already had and just updated it.

**Review by DL6ER — APPROVED** [review]
I see, I got tricked by Github's interface which seems to suggest that `moment.min.js` was removed
Screenshot at 2020-05-12 22-21-27
while it was actually just shortened to one line.

**Pull request merged**
