### PR TITLE
Revert "header: Move license header at the top"

### PR DESCRIPTION
**Pull request by XhmikosR**
Reverts pi-hole/AdminLTE#1300

### CODE REVIEW

**Comment by PromoFaux** [comment]
Did I miss some discussion around this one? What are we reverting for, here?

**Comment by XhmikosR** [comment]
I had second thoughts, because it's better if the `doctype` is first. And then I remembered that IE had historically issues with this approach. Not sure if it applies to IE 11, but it's trivial and it doesn't gain us anything, so I went with the revert.

**Comment by PromoFaux** [comment]
Thanks, helps to have an explanation. No problem for me to revert

**Review by PromoFaux — APPROVED** [review]

**Comment by XhmikosR** [comment]
For example see https://stackoverflow.com/questions/37009191/is-it-bad-practice-to-put-a-comment-before-doctype-html

**Pull request merged**
