### PR TITLE
Improve messages on the domain management pages

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
**What does this PR aim to accomplish?:**

See title

**How does this PR accomplish the above?:**

### Test 1
Adding `doubleclick.net` on the blacklist shows:
Screenshot from 2020-06-02 11-32-51

Trying to add it again shows:
Screenshot from 2020-06-02 11-32-58

### Test 2
Remove `doubleclick.net from the blacklist and add `doubleclick.net doubleclick.net`:
Screenshot from 2020-06-02 11-33-38

Again trying to add `doubleclick.net doubleclick.net` shows:
Screenshot from 2020-06-02 11-33-16

**What documentation changes (if any) are needed to support this PR?:**

None

### CODE REVIEW

**Comment by yubiuser** [comment]
Warning #2 and #4 should not state "Success" and be not green.

**Comment by DL6ER** [comment]
@yubiuser So what instead? Orange warnings?

After all, what the user asked for happened: All domains are on the list. In my opinion, it's not important if they were there before, the user wants them to be on the list and they are.

**Comment by yubiuser** [comment]
Mhh.. good point. I thought of "Warning" and orange. 

But you're right the users want to see it on the list and you just telling them they are already. No further actions of the users is required - so no "real" warning.

P.S. Maybe I was distracted by the title of the PR stating "warning". In the end it is improved success message ;-)

**Comment by DL6ER** [comment]
Thanks, I edited the title to make it more clear.

**Comment by PromoFaux** [comment]
Ignore my fat fingers forgetting how to type... If the list type has changed, is it possible to make the message say "[domain] has been moved from [type]list to [type]list", or is that too big an ask?

test com

**Comment by DL6ER** [comment]
How would you like to see this happening technically?

**Comment by PromoFaux** [comment]
I'm not 100% sure. It was just something that stuck out when I was testing

**Comment by DL6ER** [comment]
@PromoFaux I checked how we could do this but the `REPLACE` action will silently replace the entry without us noticing. When we're in FTL, we can actually catch this using an [update hook](https://www.sqlite.org/c3ref/update_hook.html), however, I checked the [PHP::SQLite3 docs](https://www.php.net/manual/en/book.sqlite3.php) and see that no such thing is available here.

So idea: Count number of domains for the same type? If this changed but the total number didn't, then the action was moving the domain from another type to here.

**Comment by DL6ER** [comment]
@PromoFaux Well, wait, we support adding two independent copies to the white- and blacklist so conversion does actually never happen?

**Review by PromoFaux — APPROVED** [review]
image
You're right, I was testing against an older version of the db schema

**Pull request merged**
