### PR TITLE
Keep "Save" button inside the content area even using boxed layout

### LINKED ISSUE #2884: Save button on boxed layout outside of content area
Screenshot at 2023-11-30 22-44-00

I think the button should align with the outer border of the content area.

### PR DESCRIPTION
**Pull request by rdwebdesign**
### What does this PR aim to accomplish?

Fix #2884

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by DL6ER** [comment]
The second commit says

> [Adding a container and a semi-transparent background](https://github.com/pi-hole/web/pull/2887/commits/89866fab77bbd27dab0201e90a96385fb5407708)

But I don't actually see a semi-transparent background:

Screenshot from 2023-12-02 08-25-06

---

It may still be nice to have it, e.g.,

Screenshot from 2023-12-02 08-32-25

Screenshot from 2023-12-02 08-38-00


Screenshot from 2023-12-02 08-35-38


``` css
.save-button-container {
	position: fixed;
	bottom: 12px;
	right: 12px;
	z-index: 10;
	background: rgba(35, 47, 52, 0.7); /* <--- changed color for variable to a semi-transparent rgba value */
	width: fit-content;
	/* border: 1px solid rgba(127, 127, 127, 0.15); */ /* <--- removed visible border */
	border-radius: 6px;
	padding: 0;
}
```

---

The root cause is that the color variable you are currently using here is not the same everywhere:

Screenshot from 2023-12-02 08-40-32

**Review by yubiuser — COMMENTED** [review]
Why do we have it both in ` settings-advanced.js` and `settings-all.lp`?

**Review by yubiuser — APPROVED** [review]

**Review by DL6ER — APPROVED** [review]
Screenshot from 2023-12-07 22-18-23
Screenshot from 2023-12-07 22-18-32
Screenshot from 2023-12-07 22-18-45
Screenshot from 2023-12-07 22-18-53
Screenshot from 2023-12-07 22-19-00
Screenshot from 2023-12-07 22-19-15

**Comment by DL6ER** [comment]
Approving even though I think we should still explore the shadow idea you had some time ago. It may give a more "plastic" feeling than the (pretty thick) semi-transparent border this PR adds.

**Pull request merged**
