### PR TITLE
Added phpstan

### PR DESCRIPTION
**Pull request by buchwasa**
So sorry for that first PR, I wasn't paying attention to the branch I was targeting.

**By submitting this pull request, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---

**What does this PR aim to accomplish?:**

This PR aims to add support for [phpstan](https://phpstan.org/) to push for higher code quality and discover any hidden or critical bugs before they are pushed into production.

**How does this PR accomplish the above?:**
This PR adds a github action to check each PR and commit for any errors. PHPStan is set to level 0, but can go up to a max level of 8. PHPStan levels are defined [here](https://phpstan.org/user-guide/rule-levels).

If this is implemented, I can maintain bumping phpstan versions if you all would like.

### CODE REVIEW

**Comment by XhmikosR** [comment]
I'd be interested in this for sure, but please split the fixes from the phpstan addition so that we land that.

Would be nice to extend it later to add PHP_Codesniffer. It's just that last time I tried it, the changes it made to the HTML part of the PHP files were a little weird.

**Comment by buchwasa** [comment]
I went ahead and dropped the fixes from phpstan, thanks for the review.

**Comment by DL6ER** [comment]
Can you already open another PR with the fixes included towards `devel`? Once we have them, we can merge this PR, this will update the diff int he new PR and your new PR will only contain the fixes, and would be ready for merge at this point as well. I'd like to avoid an intermediate situation where `phpstan` is already enabled but the fixes aren't ready (so all `devel` build fail).

**Comment by buchwasa** [comment]
Certainly

**Comment by buchwasa** [comment]
Perhaps we should test pi-hole with multiple php versions, such as 7.1 - 7.4 (or 8.0 if you're daring), that way if there are errors or issues, it can be seen if the error happens on multiple versions. Regardless of the decision of multiple php tests, it was bad on my part to use the latest php version available.

**Review by DL6ER — APPROVED** [review]
We're looking at a transition to the `PH7` engine (which implements PHP 5.3 plus extra features) in the future (hopefully sometime 2021). We may need to revert using PHPStan then because it is not exactly the same as PHP and because we have low-level access to the engine and can add functions highly-performant in low-level `C` code.

However, for the time being, this is a useful addition.

**Pull request merged**
