### PR TITLE
Supress update notice in the web interface if it is in docker

### PR DESCRIPTION
**Pull request by PromoFaux**
### **What does this PR aim to accomplish?:**

The latest docker image does not always have the latest versions of the Pi-hole components, which can lead to confusion:
 - https://discourse.pi-hole.net/t/updating-pihole-in-docker/57239/2
 - https://github.com/pi-hole/pi-hole/issues/4874

There is no need to show this flashing update notice on an Docker container.

Before: 

image

After:

image

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
- [x] I have read the above and my PR is ready for review. _Check this box to confirm_

### CODE REVIEW

**Review by yubiuser — COMMENTED** [review]
The proper solution would be to notify about a new docker tag, I guess.

**Comment by rdwebdesign** [comment]
Does `pihole` core use/show any docker version info? Does `pihole` core need to know if there is a new docker image? 

If only `AdminLTE` footer uses/shows docker tag info, I will finish my "PHP only" solution.

**Comment by yubiuser** [comment]
I think the only place where `core` needs to know if it's running on docker is to include the info in the debug log. But the actual tag is not needed to know.

**Comment by rdwebdesign** [comment]
The debug log only tests the environment var `PIHOLE_DOCKER_TAG`. 
If present it shows the docker tag, but that's it.

**Comment by PromoFaux** [comment]
Yeah, I think it is unnessacery to do any further checks for it in the core repo - debug check is fine!

**Comment by PromoFaux** [comment]
Will revisit once https://github.com/pi-hole/AdminLTE/pull/2306 is done

**Comment by PromoFaux** [comment]
Superceded by https://github.com/pi-hole/AdminLTE/pull/2306

**Pull request closed without merging**
