### PR TITLE
Update `chart.js` from 2.9.4 to 3.9.1.

### PR DESCRIPTION
**Pull request by yubiuser**
**What does this PR aim to accomplish?:**

Update `chart.js` from 2.9.4 to 3.9.1.
Needed to add `chartjs-adapater-moment.js`. I tried to be as close as possible to the old visual style. A few unnecessary options were removed, some defaults were explicitly set (e.g. `responsive: true`).

Useful for review: https://www.chartjs.org/docs/3.4.1/getting-started/v3-migration.html

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
- [x] I have read the above and my PR is ready for review. _Check this box to confirm_

### CODE REVIEW

**Comment by tingreavinash** [comment]
Hi @yubiuser,

I want to contribute to AdminLTE project, can you please help with local setup (Windows) of this project? 
I have installed NPM, Cloned this repo, `npm install`, but not able to run the project ..

**Comment by yubiuser** [comment]
Do you have a webserver installed?

**Comment by tingreavinash** [comment]
> Do you have a webserver installed?

@yubiuser, Yes, I have xampp server..

**Comment by yubiuser** [comment]
The webinterface is tightly coupled with the Pi-hole binary `FTL` which provides all the data. This binary doesn't run on Windows, but Linux. You could surely make changes to the interface without having a working Pi-hole instance, but usually your better of if you have the complete setup. I run Linux myself and edit the files directly within the web dir `/var/www/html/admin` which is a git clone of the repo.
I know @rdwebdesign  is using Windows (not 100% sure for development), maybe he could explain his setup.

**Comment by DL6ER** [comment]
Thanks for this PR. I had only limited time for testing this morning but I'll try to return to it later. It looks good to me, the only issue I've seen so far is a misplacement of the loading spinners:
Screenshot from 2022-10-05 04-38-49

**edit** I've just seen that this is an issue on `devel`, too.

**Comment by rdwebdesign** [comment]
I also see the spinners on the same place in `master`.

image
I think the spinners are there since a long time ago. 

---

**Edit:**
Before attempt any modifications, I was trying to understand where the spinners supposed to be placed and what happened.
I found out this was probably caused by [this commit](https://github.com/pi-hole/AdminLTE/commit/5624834175fb68e333b2e0d9e4e1d86953776ec9). 

The spinner uses a fontawesome icon. This icon is replaced (and resized and repositioned) by script.
This change was made almost 2 years ago.

**Comment by yubiuser** [comment]
Spinner is fixed by https://github.com/pi-hole/AdminLTE/pull/2385
Screenshot at 2022-10-05 09-16-52

**Review by DL6ER — DISMISSED** [review]

**Review by PromoFaux — APPROVED** [review]

**Pull request merged**
