### PR TITLE
Fix query string authentication for API calls

### LINKED ISSUE #2326: All API calls with auth="..." are broken
### Versions

- Pi-hole:  5.12
- AdminLTE:  5.17
- FTL:  5.14.1

**It only started occurring after the updates from yesterday.**

### Platform

- OS and version:  Debian 10

- Platform:  Raspberry Pi

### Expected behavior

When for example making the request http://192.168.1.68/admin/api.php?getForwardDestinations=""&auth="66f5f0cf90a042cd064aa3807ebb86e4191665801f0812013c110ac3cf4de344"

I would expect a response.

### Actual behavior / bug

That request just returns an empty array []. If you make the request in a browser that's logged into the web interface, it does give a response. However you would expect it to work just with the auth="...".

### Additional context

This breaks almost all calls of the API as used in my application Pi-hole Remote (iOS); except calls like summary(Raw) and overTimeData10mins as they do not require the auth.

### PR DESCRIPTION
**Pull request by rdwebdesign**
### What does this PR aim to accomplish?:

Closes #2326 

### How does this PR accomplish the above?:

Passing the api flag to the password verification function.

### What documentation changes (if any) are needed to support this PR?:

none

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
- [x] I have read the above and my PR is ready for review. _Check this box to confirm_

### CODE REVIEW

**Comment by PromoFaux** [comment]
Looks Gouda to me

**Review by PromoFaux — APPROVED** [review]

**Comment by jojost1** [comment]
@PromoFaux Any word on when this fix can be released? I would really appreciate if this could be hotfixed (the bug breaks all authenticated API calls and therefore many third party Pi-hole utilities) but I don't know how you decide if it's worth to hotfix something 😄

**Comment by PromoFaux** [comment]
No reason why it can't go out today, just waiting for another couple of pairs of eyes on it from the team before I hit the buttons!

https://github.com/pi-hole/AdminLTE/pull/2332

**Comment by jojost1** [comment]
I appreciate it! ❤️

**Comment by baderdj** [comment]
Looks like server stats aren't allowed with this patch.  Things like Temperature, CPU, Memory show an error while fetching data.

**Comment by PromoFaux** [comment]
> Things like Temperature, CPU, Memory show an error while fetching data.

This is expected: https://github.com/pi-hole/AdminLTE/pull/2332#issuecomment-1236343579

**Comment by baderdj** [comment]
> > Things like Temperature, CPU, Memory show an error while fetching data.
> 
> This is expected: [#2332 (comment)](https://github.com/pi-hole/AdminLTE/pull/2332#issuecomment-1236343579)

oh ok.  Not a huge miss but it was nice to see on the Pi-hole Remote app.

**Pull request merged**
