### PR TITLE
Add checkbox (save state in localstorage) to toggle between bar and smooth

### PR DESCRIPTION
**Pull request by PromoFaux**
**By submitting this pull request, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
**What does this PR aim to accomplish?:**

Title

pleasingeveryone

uses `localstorage` no need to save this in `setupVars`, which allows for multiple users of the dashboard (from different computers) to toggle to their preference. 

Could do the same with  boxed layout maybe...

### CODE REVIEW

**Comment by XhmikosR** [comment]
LGTM, but it seems all other setting in that page apply after clicking Save, so maybe we should be consistent here?

**Comment by DL6ER** [comment]
I mean, we switched from smoothed graphs to bar charts for a reason (the data is actually discrete). However, I have no issues with allowing users to go back to the (wrong) way they are used to. After all, the information contained here isn't critical at all.

I concur with @XhmikosR's objection that an immediately triggered saving does not really seem to fit here. I furthermore like the idea to do the same with boxed layout. So how about moving these two into a *new* tab of the settings page which is lacking a Save button (instead a text that changes are applied immediately)? This page can be extended in the future when more per-browser things are available (such as time zone settings, https://momentjs.com/timezone/docs/).

**Comment by PromoFaux** [comment]
Sounds good to me. The reason I chose local storage as a way of remembering the selection was because it didn't seem like it was a feature worthy of saving back out to the config file. Anecdotally, i have seen less people asking for a return to the smooth graphs than I have seen people praising the new ones.

Concur that maybe we have a "per-browser" preferences section.

**Review by DL6ER — APPROVED** [review]
We should really rename this new tab, however, it may become clearer how it should look like when we add more stuff to it.

**Pull request merged**
