### PR TITLE
Use the `setupVars.conf` option `TEMPERATUREUNIT`, plus slight rearrangement of settings page

### PR DESCRIPTION
**Pull request by rdwebdesign**
## What does this PR aim to accomplish?

Allow the selection of temperature unit shown on the web interface via `setupVars.conf`, like other interfaces (PADD/chronometer) already do.

Currently the web interface always defaults to "C" (Celcius). The user must manually select the unit on Setting page for every device/browser used.

Note:
The suggest code here will use a global unit and remove the ability to use different units on each device (which was probably never the desired behavior).

## How does this PR accomplish the above?

Changing the code to use a new behavior:
- if the option `TEMPERATUREUNIT` is set in `setupVars.conf` file, the value will be used.
- if there is no unit set in `setupVars.conf`, but the browser has an old value set on `locastorage`, the `localstorage` value will be used and stored in `setupVars.conf` file.
- if there is no unit set in `setupVars.conf` or `localstorage`, "C" will be used as default value.

Also:
- The temperature unit will be set GLOBALLY and not per browser.
- changing the value on the web interface WILL CHANGE `setupVars.conf`.

## Link documentation PRs if any are needed to support this PR:

The [TEMPERATUREUNIT description](https://github.com/pi-hole/docker-pi-hole/#optional-variables) on docker-pi-hole repository will need to be updated to reflect the new behavior

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by PromoFaux** [comment]
App appears to work, though regarding this part:

> The temperature unit will be set GLOBALLY and not per browser.

With that in mind, we should probably move this out of the `Per-browser` settings box, and into the `Web interface settings` box?

**Comment by rdwebdesign** [comment]
> With that in mind, we should probably move this out of the Per-browser settings box, and into the Web interface settings box?

I agree.

**Comment by PromoFaux** [comment]
I think it looks fine, however it now introduces something else... Changing the temperature unit is automatically updated when switching between them without having to press save...

The other options in that same dialog require the usage of the save button. Two suggestions:
  - Make the others change on selection rather than pressing save
  - Separate the temperature unit selection out to another box / separate part of the same box to show that Save is not needed for this item

**Comment by rdwebdesign** [comment]
Yeah... I notice this behavior.

What do you think about this?
web_api

**Comment by PromoFaux** [comment]
Yep - that looks good to me

**Review by PromoFaux — APPROVED** [review]

**Pull request merged**
