### PR TITLE
Optimize how scripts loads.

### PR DESCRIPTION
**Pull request by Gontier-Julien**
Signed-off-by: Gontier Julien <gontierjulien68@gmail.com>

**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

Improvement of the loading of the scripts by making them loads asynchronously.

**How does this PR accomplish the above?:**

-Added `async` to the scripts on the `.header.php` file

**What documentation changes (if any) are needed to support this PR?:**

None

### CODE REVIEW

**Comment by Gontier-Julien** [comment]
Hopping this is better like this @dschaper  ^^

**Comment by PromoFaux** [comment]
Not 100 % on this one. Query log no longer loads after applying these patches locally.
image

**Comment by Gontier-Julien** [comment]
It apply on my raspberry pi and I tested it on firefox/chrome/brave/firefox and chrome on android/safari, chrome and firefox on ios, and it working perfectly fine.
Maybe this juste need more testing by some user.
But before doing any PRs i always test all my change, and since I made those change I haven't noticed any bugs.

**Comment by schorschfunke** [comment]
For me it works well too on Chromium and Firefox on Android.  Self compiled pihole on archlinuxarm for RPi4 (aarch64)

**Comment by Gontier-Julien** [comment]
@PromoFaux what setup do you have exactly ? So I can test it see if I can reproduce your problem.

**Comment by XhmikosR** [comment]
You can't use async like that; the order of execution is not guaranteed then. And this adds an extra point of failure that the maintainers have to remember.

So, if a script needs another script and it's loaded async, this will break.

**Comment by Gontier-Julien** [comment]
Maybe loading the scripts in the defer way would be better ? because script while execute in orders.

**Comment by Gontier-Julien** [comment]
Okay so i've experienced with the `defer` option we can make all scripts loads with defer and keep all scripts execution in the same order, and it doesn't break anything.

@XhmikosR what are you thinking about this change is this better ?

**Comment by XhmikosR** [comment]
I don't think it's worth bothering with this. There's no need to add another POF especially since Pi-hole is used mostly locally.

**Comment by Gontier-Julien** [comment]
Okay no problems, I will close this pull request.

**Pull request closed without merging**
