### PR TITLE
v5.15

### PR DESCRIPTION
**Pull request by PromoFaux**

### CODE REVIEW

**Review by yubiuser — COMMENTED** [review]
Should this really be a `.patch`? I think we added some stuff that could deserve a `v5.15`

**Comment by PromoFaux** [comment]
OK, sure, happy with 5.15

**Review by yubiuser — APPROVED** [review]

**Comment by rdwebdesign** [comment]
@yubiuser 

Do you think this issue (https://github.com/pi-hole/AdminLTE/issues/2347) can be fixed later?

**Comment by yubiuser** [comment]
Yes. We have some more "severe" bugs fixed in this v5.15. The fix for https://github.com/pi-hole/AdminLTE/issues/2347 still needs to be written and can easily be a hotfix.

**Review by rdwebdesign — APPROVED** [review]

**Pull request merged**
