### PR TITLE
#1777  "Remember me for 7 days" doesn't work if you log in from Recent Queries

### PR DESCRIPTION
**Pull request by chrismiceli**
**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [ x ] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [ x ] I have made only one major change in my proposed changes.
- [ x ] I have commented my proposed changes within the code.
- [ x ] I have tested my proposed changes.
- [ x ] I am willing to help maintain this change if there are issues with it later.
- [ x ] I give this submission freely and claim no ownership.
- [ x ] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ x ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [ x ] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

`Attempts to resolve https://github.com/pi-hole/AdminLTE/issues/1777`

**How does this PR accomplish the above?:**

`By setting the cookie in the case of logging in from a deep link`

**What documentation changes (if any) are needed to support this PR?:**

`None as this should be the expected behavior.`

### CODE REVIEW

**Comment by chrismiceli** [comment]
I'm not sure why DCO worfklow is complaining as it appears my commit has been signed off as far as I can tell.

**Comment by chrismiceli** [comment]
Is there anything else I need to do to facilitate getting this merged?

**Comment by DL6ER** [comment]
No, sorry for the delay on reviewing this. As you know, Pi-hole is only a volunteer project and sometimes (yes, I know, I should say "often"), we come here to fix some things on our own but don't get around reviewing external contributions. You have my apologies and I'll merge your PR given that all automated tests pass.

**Comment by chrismiceli** [comment]
> 
> 
> No, sorry for the delay on reviewing this. As you know, Pi-hole is only a volunteer project and sometimes (yes, I know, I should say "often"), we come here to fix some things on our own but don't get around reviewing external contributions. You have my apologies and I'll merge your PR given that all automated tests pass.

No worries. I was just making sure I was following the process appropriately and no one was waiting on me.

**Review by PromoFaux — APPROVED** [review]

**Pull request merged**
