### PR TITLE
Fix (and simplify) mass deletion of several tables

### PR DESCRIPTION
**Pull request by DL6ER**
# What does this implement/fix?

Fix (and simplify) mass deletion of DHCP lease, diagnosis messages, and local DNS/CNAME records

---

**Related issue or feature (if applicable):** see Discourse thread

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

### CODE REVIEW

**Review by yubiuser — COMMENTED** [review]
Currently, there is no mass-deletion of local DNS/CNAME records at all.

Screenshot at 2024-05-30 14-15-04

**Comment by DL6ER** [comment]
@yubiuser You are right, for this table only the "(and simplify)" part applies

**Review by yubiuser — CHANGES_REQUESTED** [review]
This change causes a 'undefinded' message to pop up when more then one item is deleted. Also the count is off: when more then one item is deleted it will always success with 1 item deleted, except when only *the last* item in a table is deleted it will show 2 items deleted

Screenshot at 2024-06-01 21-33-28

**Comment by DL6ER** [comment]
@yubiuser looking at this, this is actually not a new bug but in fact a more general bug of our toast notification system. Previously, we printed a single toast for deleting multiple entries and updated this on success/fail. Now we print individual toasts but can only update the last one (due to this aforementioned limitation). I guess we need to cluster again but - as the deletion events get fired async and individually, I'm not actually sure what would be the best Javascript handling to actually report about errors or success.

**Comment by rdwebdesign** [comment]
Why do we need the initial blue message saying "Deleting message..." and then update the message?

I think we could simply show the final message (success or error).

**Comment by yubiuser** [comment]
I think we have all those "doing xxx" messages because on slower devices it might need some time before the operation finished and success/failure is displayed. So the users know their click triggered an action.

**Comment by rdwebdesign** [comment]
Hmmm...
Do we need to update the initial message?

In other words: can we simply display one toast with the initial "Doing xxxxxx..." message and when the answer is received we display another toast with the final message (not updating the initial one)?

**Comment by yubiuser** [comment]
This should be fine I guess.

**Comment by rdwebdesign** [comment]
@DL6ER

You have a [related PR](https://github.com/pi-hole/web/pull/2792) (at least in part) where you made some changes to `showAlert()`. I think that changes were intended to fix the toast issues we are seeing above.

**Comment by DL6ER** [comment]
Oh, more than half a year ago PR which totall escaped me. Closing this one as it is a duplicate. I will port the changes into the older PR and rebase it on latest `development-v6`.

**Pull request closed without merging**
