### PR TITLE
Add Star Trek LCARS theme

### PR DESCRIPTION
**Pull request by rdwebdesign**
Signed-off-by: rdwebdesign <github@rdwebdesign.com.br>

**By submitting this pull request, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

Adds a new pi-hole theme based on the Star Trek LCARS visual (as a tribute and using the "fun" suggestion in the Contributors Guide)

**How does this PR accomplish the above?:**

The new visual was achieved by adding a new CSS theme only.
- This new theme DOES NOT change files from the "vendor" directory.
- This new theme DOES NOT change files from other themes.
- This new theme only includes new CSS files (and Fonts). 

**What documentation changes (if any) are needed to support this PR?:**

None, for now.

### CODE REVIEW

**Comment by yubiuser** [comment]
Wow, that's impressive!

Bildschirmfoto zu 2021-10-24 12-50-27
Bildschirmfoto zu 2021-10-24 12-50-43
Bildschirmfoto zu 2021-10-24 12-50-50
Bildschirmfoto zu 2021-10-24 12-51-01

**Comment by DL6ER** [comment]
Thanks. I noticed a few inconsistencies (but that is only minor stuff):

Screenshot from 2021-10-24 15-46-26

The Pi-hole diagnosis system icon is covered by the number (if present). Not sure if this is intended, just mentioning this here.

---

Screenshot from 2021-10-24 15-46-32

Screenshot from 2021-10-24 15-47-01

Screenshot from 2021-10-24 15-53-01

Screenshot from 2021-10-24 15-53-08


Inner button text arrangement looks off in some smaller buttons.

---

Screenshot from 2021-10-24 15-46-53

The disabled button has a visible knob in disabled state.

---

Screenshot from 2021-10-24 15-48-31

The information stored in the color gradient is somewhat lost on the network page when the gradient is not really visible.

---

Else than that this really looks great.

**Comment by rdwebdesign** [comment]
@DL6ER,

- I fixed the ugly disabled toggle button (I really missed that one).
- I also changed the gradient of the network table to different colors. I tried to keep dark tones, but with visible contrast. See if it's better.
- The Pi-hole diagnosis system icon was cover as a side effect of other changes. It's fixed now.

As for the buttons: text alignment at the bottom right was intentional (just like the sidebar alignment). If this is too bad or not in accordance with the rules, let me know and I'll place the text back to the original alignment.

**Comment by rdwebdesign** [comment]
@yubiuser, 
I saw you tried this PR. 

What do you think about it? Any suggestions?

**Comment by yubiuser** [comment]
I think it is an impressive theme and does fit into Pi-hole's overall Star Trek theme very well. Personally, its't nothing I would use for every-day, especially the font's I don't like very much. But this is my personal taste and should not prevent this PR from being part of Pi-hole. I'm sure a lot of people will like and use it.
I just played with it the last 10 minutes and did not see any visual bugs. Give us a note if you think the PR is ready for review.

**Comment by rdwebdesign** [comment]
@yubiuser 

Thank you for your comments.

I used these fonts to get the condensed look used in Star Trek panels. This can be modified as needed.

I like to hear more opinions, but personal taste is important.
I generally don't use dark themes. Usually I use the clear theme.

I know it's not everyone's choice, but this theme was created for those who are fans and like dark themes. I think it works best on desktops, but it's also been tested on phones and tablets.

Do you see any issues if I mark this as ready for review?

**Comment by yubiuser** [comment]
> Do you see any issues if I mark this as ready for review?

No. 

> I know it's not everyone's choice, but this theme was created for those who are fans and like dark themes.
> This can be modified as needed.

If you like it and it looks like you imagined it to be, that's fine. Design choices do and never will please everyone.

**Comment by rdwebdesign** [comment]
I agree. 
Design choices are personal..., but I accept ideas.

**Review by yubiuser — APPROVED** [review]

**Pull request merged**
