### PR TITLE
Add class "breakall" also to the code fields in the other tables.

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
**What does this PR aim to accomplish?:**

Enable wrapping of too long lines in the group management tables.

**How does this PR accomplish the above?:**

Add class `breakall` to all `<code>` tags in all tables.

**What documentation changes (if any) are needed to support this PR?:**

None

### CODE REVIEW

**Comment by DL6ER** [comment]
Confirmed working here: https://discourse.pi-hole.net/t/restore-ability-to-add-blacklists-in-bulk/28091/34?u=dl6er

**Comment by XhmikosR** [comment]
Are you sure you are not missing the CSS changes?

BTW maybe we should use `text-break-all`

**Review by PromoFaux — DISMISSED** [review]

**Comment by DL6ER** [comment]
Resolved merge conflicts.

@XhmikosR No, `code.breakall` is defined in `style/pi-hole.css`

**Review by PromoFaux — APPROVED** [review]

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/restore-ability-to-add-blacklists-in-bulk/28091/37

**Comment by yubiuser** [comment]
Current devel branch: breakall doesn't play nice with Group Management/Domains and long entries

Bildschirmfoto zu 2020-06-03 23-18-51

**Comment by DL6ER** [comment]
The solution could be to give a maximum cell width here, how large would be appropriate?

**Comment by yubiuser** [comment]
Large enough that type renders correctly - maybe set type to a fixed width? 
It's fine on master, so this "bug" must have been introduced with some recent changes.

Bildschirmfoto zu 2020-06-04 09-44-51

**Comment by DL6ER** [comment]
I think the only change to this table since `master` was 
 https://github.com/pi-hole/AdminLTE/pull/1367

What do you think @XhmikosR ?

**Comment by XhmikosR** [comment]
* `display` is a non-existent class; could be this class was magically doing something in `dataTables`, so see my last point
* `cellspacing="0"` is invalid and doesn't have any effect
* `width="100%"` is invalid too, but I didn't touch this in devel

Please paste the exact snippet so that I can reproduce. Also, browser info/OS.

@DL6ER that is why I have #1354. For example, if we want a table to be responsive we should do this in the markup so that it's clear.

PS. this behavior seems normal to me with the `breakall` addition.

**Comment by XhmikosR** [comment]
We should probably be using `pre` and not `code`. And remove the `breakall` class.

I need the aforementioned info so that I can look into it.

**Comment by yubiuser** [comment]
@XhmikosR: Linux Mint, 19.3, Chrome 83, Firefox 77. 

```
(^|[-_.]+)(m?a(d((vert(s|is(ing|e?ments?))?|im(age|g)s?)|([vx]|s(e?rv(er?|ice)?s?)?)|track(ers?|ing))?|ff(iliat(es?|ion))?|nalytics?)|b((anner|eacon)s?)|count(ers?)?|pixels?|stat(s|istics?)?|t(elemetry|ra(ffic|ck(ers?|ing))))[-_]*[0-9]*[-_.]
```

**Comment by XhmikosR** [comment]
Yeah, the columns need width AFAICT:

image

But it's not a blind change because on mobile this will be worse.

BTW I just noticed the tooltip wrongfully includes HTML.

**Comment by yubiuser** [comment]
https://github.com/pi-hole/AdminLTE/issues/1458

**Pull request merged**
