### PR TITLE
CI: remove no longer needed steps

### PR DESCRIPTION
**Pull request by XhmikosR**
The latest `actions/setup-node` prints this info by default

### CODE REVIEW

**Comment by XhmikosR** [comment]
BTW this reminds me @dschaper assuming everyone always opens a PR and nothing gets merged directly, we can change the CI to just run on PRs and master. Let me know about it and also if I should backport this change to the other repos.

**Comment by dschaper** [comment]
Nothing should ever hit any of the protected branches without a PR. That would be `master` `development` (or `devel` but that branch should be named `development`) and `release/*`.

**Comment by XhmikosR** [comment]
Cool, I'll make another PR later. We can merge this one.

**Pull request merged**
