### PR TITLE
Fix new query types (retired, retired DNSSEC and in-progress) showing…

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
**What does this PR aim to accomplish?:**

Fix https://discourse.pi-hole.net/t/l-b-dns-sd-udp-werden-zahlreich-geblockt/42312

**How does this PR accomplish the above?:**

Fix new query types (retired, retired DNSSEC and in-progress) showing up as blocked queries on the long-term data pages

**What documentation changes (if any) are needed to support this PR?:**

None

### CODE REVIEW

**Comment by PromoFaux** [comment]
I'm really sorry to have missed this...

There are conflicts for now (Unless this already got fixed somewhere else?)

**Comment by PromoFaux** [comment]
@DL6ER please fix merge conflicts and ping me for another review (or close if this has already been fixed somewhere else)

**Comment by DL6ER** [comment]
Well, yes, apparently @yubiuser resolved this one week *after* I opened this PR (https://github.com/pi-hole/AdminLTE/pull/1743). This can be closed, thanks for checking.

**Comment by yubiuser** [comment]
Sorry, didn't noticed your PR.... your solution would have been more elegant as it defines `blocked` and `permitted` groups.

**Comment by DL6ER** [comment]
No worries. Looking at your PR, it very much looks like I forgot about my own PR only one week after...
This has already moved into FTL for v6.0 where we have a boolean function `is_blocked(status)` that is used in many places in the code and will complain if new status types are added without being handled in there.

**Pull request closed without merging**
