### PR TITLE
Use the minified animate.css file.

### PR DESCRIPTION
**Pull request by XhmikosR**
**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [ ] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

By default, bootstrap-notify only needs a few classes, but at least this is less bloated.

I could only keep the needed default animations in another PR if you guys prefer that. The difference will be huge, but it will mean we'll need to customize a vendor file.

I only tested this on the browser, so it needs another test just to be 100% safe.

### CODE REVIEW

**Comment by DL6ER** [comment]
> I only tested this on the browser, so it needs another test just to be 100% safe.

Which kind of tests?

**Comment by XhmikosR** [comment]
Just if everything looks good, although it should be moot indeed. Just merge this :)

**Comment by PromoFaux** [comment]
> but it will mean we'll need to customize a vendor file.

I'd rather not to that if we can help it.

**Comment by XhmikosR** [comment]
Yeah, that's why I went with the minified file for now to keep things simple :)

**Review by PromoFaux — APPROVED** [review]

**Pull request merged**
