### PR TITLE
Expanding the modern look to rest of the interface

### PR DESCRIPTION
**Pull request by Gontier-Julien**
Signed-off-by: Gontier Julien <gontierjulien68@gmail.com>

**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

It expand the modern look to the rest of the interface.

**How does this PR accomplish the above?:**

-Change `.nav-tabs-custom`  from `border-radius:3px` to `border-radius:10px !important`.
-Change `.nav-tabs-custom > .nav-tabs` from `border-top-left-radius:3px` and `border-top-right-radius:3px`to `border-top-left-radius: 10px !important` and `border-top-right-radius: 10px !important`
-Change `.nav-tabs-custom > .tab-content` and `.box-footer` from `border-bottom-left-radius:3px` and `border-bottom-right-radius:3px`to `border-bottom-left-radius: 10px !important` and `border-bottom-right-radius: 10px !important`

**What documentation changes (if any) are needed to support this PR?:**

None

### CODE REVIEW

**Comment by DL6ER** [comment]
Do you have a screenshot showing your changes?

**Comment by DL6ER** [comment]
``` diff
-.nav-tabs-custom > .tab-content { 
+.nav-tabs-custom > .tab-content {
-}
\ No newline at end of file
+}
```

should fix the linting errors

**Comment by Gontier-Julien** [comment]
In the left you have without my modification and in the right with it!.
It just a small aesthetics change to make the buttons look a bit better.
[example](https://user-images.githubusercontent.com/52894530/106788130-774ac780-6648-11eb-809c-aaf3af2de552.png)

**Comment by dschaper** [comment]
It's way too rounded for me.

**Comment by Gontier-Julien** [comment]
It up for debate and personal taste after this so maybe play around a bit and tell with you think is the sweet spot ^^

**Comment by dschaper** [comment]
The template that I have in mind for the next iteration uses .25rem for the radius on buttons.

**Comment by dschaper** [comment]
https://vue.architectui.com/architectui-vue-pro/#/elements/buttons-shadow

**Comment by Gontier-Julien** [comment]
@dschaper you're in the wrong pull request for the button and maybe look with what @PromoFaux proposed.

**Comment by dschaper** [comment]
I'm talking with him right now actually.

**Comment by Gontier-Julien** [comment]
@dschaper no problem.
But with .25rem it while not change much (if at all) compared of the current design of the button.

**Comment by dschaper** [comment]
Yeah, I know.

**Comment by PromoFaux** [comment]
I should have better reviewed the rounded corners in the last few PRs (or at least discussed it with the rest of the team) 


original:
image

10px:
image

5px:
image

.25rem
image


Now, I know this PR is discussing a different part of the interface, but I think this serves as a good a place as any to discuss, with that said my personal preference here is 5px

**Comment by dschaper** [comment]
I'm not going to pick this as a hill for me, but I'd ditch the px as a value, and even then 5px looks too rounded still. 

Maybe something like the top widgets on https://vue.architectui.com/architectui-vue-pro/#/dashboards/management 

or

https://vue.architectui.com/architectui-vue-pro/#/dashboards/project-management

**Comment by Gontier-Julien** [comment]
@dschaper just a quick question, what wrong with making some part of the interface a little rounded ?
I know some people don't like rounded interface and it totally fine.
But maybe can we make a option for people that like it that way ?
It all personal taste after all.

**Comment by dschaper** [comment]
Quick Answer, I don't like the look. And yes it's personal. 

I don't think adding more options to decide if you want to change the radius of the elements is useful, that's going to be a lot of work for a web interface that is planned on being replaced.

**Comment by Gontier-Julien** [comment]
Oh that cool when the new interface while be here ?
And yeah i totally understand this problem ^^

**Comment by PromoFaux** [comment]
> Oh that cool when the new interface while be here ?

[Soon™](https://wowwiki-archive.fandom.com/wiki/Soon) is about as good an answer as you'll get :) There is some work going on in [this branch](https://github.com/pi-hole/AdminLTE/tree/new/FTL_is_my_new_home) for the 6.0 release (which will feature a new api). Beyond that, we're toying with the idea of a total framework change (see linked ui framework above). But no timelines are really set in stone

For this one after a bit of internal discussion - can we pare the roundedness of the corners back to `.25rem` instead of `10px`, please?

**Comment by Gontier-Julien** [comment]
Exited to see this then ^^
Maybe i close those two pull request and you cloud just revert back this pull request ?
https://github.com/pi-hole/AdminLTE/pull/1691

**Pull request closed without merging**
