### PR TITLE
Make buttons nicer to look at.

### PR DESCRIPTION
**Pull request by Gontier-Julien**
Signed-off-by: Gontier Julien <gontierjulien68@gmail.com>

**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

It just make all the buttons nicer.

**How does this PR accomplish the above?:**

-Make `border-radius: 6px !important` of `.btn`

**What documentation changes (if any) are needed to support this PR?:**

None

### CODE REVIEW

**Comment by DL6ER** [comment]
Do you have a screenshot showing your changes?

**Comment by DL6ER** [comment]
Adding the missing newline at the end of the file should fix the linting errors here as well.

**Comment by dschaper** [comment]
I personally don't like the radius on the buttons, it's too much and needs to be reduced to a lower value.

**Comment by PromoFaux** [comment]
Yeah, I've been playing with this a bit - 5px looks nicer, I think (mea culpa: I accepted the 10px beforehand)

**Comment by Gontier-Julien** [comment]
In the left you have without my modification and in the right with it!.
It just a small aesthetics change to make the buttons look a bit better.
106788130-774ac780-6648-11eb-809c-aaf3af2de552

**Comment by PromoFaux** [comment]
Can you do another screenshot with 5px, please?

**Comment by Gontier-Julien** [comment]
here goes you go
5px

**Pull request closed without merging**
