### PR TITLE
Fixes #1227 Fix possible warning when unlinking files

### LINKED ISSUE #1227: PHP Warning:  unlink(../custom_disable_timer)
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

3

---
**Expected behaviour:**

When disabling pihole using the web interface a timing file is generated (custom_disable_timer) in the www-root directory. This file will be removed later when the service is reenabled.

**Actual behaviour:**

When PHP display_errors configuration variable is set to ON a warning can be raised when the file does not exists, which is the case of permanently service disabling.

This warning blocks the web interface spinning animation associated to the action (disabling the service).

**Steps to reproduce:**

Enable PHP display_errors configuration environment and play with disabling/enabling the service using the web interface.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/uuy4bp614g (uuy4bp614g)

**Troubleshooting undertaken, and/or other relevant information:**

Disabling the PHP display_errors setting solves the issue.

### PR DESCRIPTION
**Pull request by willemstuursma**
Signed-off-by: Willem Stuursma-Ruwen <willem@stuursma.name>

**By submitting this pull request, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

This PR aims to fix #1227.

**How does this PR accomplish the above?:**

I have chosen to use the silence operator (`@`). An alternative would be to use `file_exists()`, but that still allows a race condition where the file is deleted after the `file_exists` call but before the `unlink` call.

**What documentation changes (if any) are needed to support this PR?:**

N/A.

### CODE REVIEW

**Comment by DL6ER** [comment]
I'd actually prefer the `file_exists()` way of doing things. The chance for a race collision in to subsequent function calls is highly unlikely, I'd say.

**Review by PromoFaux — CHANGES_REQUESTED** [review]
Yeah, I think I would also prefer the explicit `if(file exists) unlink`, after some reading.

I mean, it's highly unlikely, but PHP may not be able to remove the file for some other reason... using `@` will hide that information, making debugging difficult.

**Comment by willemstuursma** [comment]
Sorry, I didn't notice the earlier comments. I'll get to it later this week.

**Comment by un99known99** [comment]
as found out: it will appear while 
using the option "permanently disable" then re-enable pihole blocking ...


2020-06-07 22:41:01: (mod_fastcgi.c.421) FastCGI-stderr: PHP Warning: unlink(../custom_disable_timer): No such file or directory in /var/www/html/admin/api.php on line 72
2020-06-07 22:41:11: (mod_fastcgi.c.421) FastCGI-stderr: PHP Warning: unlink(../custom_disable_timer): No such file or directory in /var/www/html/admin/api.php on line 47

**Review by DL6ER — APPROVED** [review]

**Review by PromoFaux — APPROVED** [review]

**Pull request merged**
