### PR TITLE
Better donate button - navbar

### PR DESCRIPTION
**Pull request by rdwebdesign**
**By submitting this pull request, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

Replaces the image button and replaces it with a simple button.

**How does this PR accomplish the above?:**

Replacing the image with a HTML + CSS button
navbar_donate

**What documentation changes (if any) are needed to support this PR?:**
none.

### CODE REVIEW

**Review by yubiuser — COMMENTED** [review]
Didn't know that this menu existed at all...
The whole section needs a few adjustments for mobile...
Screenshot_20220328-063603
Screenshot_20220328-063540
Screenshot_20220328-063452
Screenshot_20220328-063521


P.S. Thee `img/donate.gif` can be deleted, this is the only place we use it.

**Comment by rdwebdesign** [comment]
I fixed the small and medium screens version.
It looks better now.

**Review by yubiuser — CHANGES_REQUESTED** [review]
Now it's only the dark theme on mobile that need a bit tweaking
Screenshot_20220328-201314

**Comment by rdwebdesign** [comment]
Are you sure the new CSS was correctly loaded?
Are there any cached CSS files?

**Comment by yubiuser** [comment]
Scratch my last comment. It was an issue with the local repo. All fine here.

**Review by yubiuser — APPROVED** [review]

**Pull request merged**
