### PR TITLE
Add support for tracking static DHCP hostnames separately

### PR DESCRIPTION
**Pull request by DroidFreak32**
* This will let Pi-Hole resolve hostnames even if they are not active.
* Addresses https://github.com/pi-hole/pi-hole/issues/3600 and #2286

Signed-off-by: DroidFreak32 <rushabshah32@gmail.com>

---
- **What does this PR aim to accomplish?:**

This PR will add support to have a separate file that tracks DHCP hostnames
With this approach, any Static leases can still be resolved even if they are not under active leases.
We no longer will have to maintain a separate Local DNS entry in situations where one needs to constantly update DHCP static leases and has PiHole as their primary DNS resolver.

- **How does this PR accomplish the above?:**

This PR paired with https://github.com/pi-hole/pi-hole/pull/4865 adds an extra step while adding and removing static leases
While adding a new lease, `webpage.sh`'s `adddhcphostname` is only called if we have IP and Hostname provided.
The bash script that is called adds a comment line which only contains the MAC address and the next line has IP + hostname.
The comment line containing MAC address is to help the removal function to identify the correct line

While removing the static lease, the current code does not have information other than the MAC address of the entry
Inorder to minimize code changes (Also, I don't have any experience with PHP/js), the MAC address is provided as an argument and the bash function that is called will match this mac and delete only the line containing the IP + Hostname after it.

In terms of upgrades, it should stay unimpacted since these entries shouldn't interfere with the existing ones

- **What documentation changes (if any) are needed to support this PR?:**

*Replace this with a detailed list of any necessary changes*

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
- [x] I have read the above and my PR is ready for review. _Check this box to confirm_

### CODE REVIEW

**Comment by DroidFreak32** [comment]
PS I forgot to mention the reason this PR modifies existing functions and not new functions (unlike the PR in the "core" repo), is the added benefit of not modifying the code in `teleporter.php` which calls the existing function:
https://github.com/pi-hole/AdminLTE/blob/94bba3ef9d67ed5c9261a0ac79dbf42f0d7ed381/scripts/pi-hole/php/teleporter.php#L510

**Comment by yubiuser** [comment]
This PR makes this the new default for every static hostname added. I was thinking if this should be an option users can check on per-mac-level? So they could device for every entry if they would like to add a DNS entry.

**Comment by DroidFreak32** [comment]
> This PR makes this the new default for every static hostname added. I was thinking if this should be an option users can check on per-mac-level? So they could device for every entry if they would like to add a DNS entry.

Could you clarify more on the per-mac-level option?
This PR will add a static hostname _only_ if both IP and hostname are provided.
If the hostname is not provided, there won't be any entry added to the static lease file.
Should the user decide they don't want to add a DNS entry, they can just leave the hostname blank (which is how it works currently- the hostname gets set to 'nohost' / _unknown_)

**Comment by yubiuser** [comment]
> Should the user decide they don't want to add a DNS entry, they can just leave the hostname blank (which is how it works currently- the hostname gets set to 'nohost' / unknown)

But they might want to set a hostname if the lease is active, but not when there is no active lease. With your PR you change the default behavior, but I would like to make this optional. 

> Could you clarify more on the per-mac-level option?

What I mean is: not just a singel generic option "Add Local DNS records for hostnames of static assignments" but to have an option **for each single assignment**

**Comment by DroidFreak32** [comment]
@yubiuser I see your point now.
For every new assignment, you want there to be an option (like a checkbox in the GUI) that asks the user if they want to have it as a permanent Local DNS entry or not.
In that case, this would need to be a larger change in the web UI code as well to have a checkbox and capture the value from it.

That would also cause the `teleporter.php` code to change because teleporter currently calls `addStaticDHCPLease` which during import won't have data of this checkbox. With my PR it will automatically add to static-lease file if Hostname is provided.

An alternate (easier) idea is to have the teleporter manually also copy the static lease file, id like to know your thoughts on this part.

I can attempt to get the UI change to implement the per-mac-level option but this will need to be thoroughly tested (I have no web development experience)

**Comment by DroidFreak32** [comment]
@yubiuser Can you review the new push? I have added a checkbox in the WebUI which gives user the option mentioned
image
This is rebased on the latest devel, I'm not sure what the PHP-CS-Fixer failure is, it does not mention anything in it :sweat_smile:

**Comment by rdwebdesign** [comment]
You can see what is wrong clicking on the "details" link for the failed test.
image

In your case, this is the link: https://github.com/pi-hole/AdminLTE/runs/7777190493?check_suite_focus=true

It is asking to change the code around line 188.
(lines starting with `-` should be removed, lines starting with `+` should be added).

---
Note:
If you have PhpCsFixer installed locally, you can fix the file before you push it.

**Comment by yubiuser** [comment]
@DroidFreak32 

We had a quite intensive internal discussion around your PRs and the new function it would add. The majority's decision was to not implement that. The use case is a quite rare one and there are other ways to add DNS resolution for non-active static DHCP hostename leases (like using non-overlapping DHCP pools and manually adding Local DNS records). I suggest you contact the `dnsmasq` mailinglist (https://lists.thekelleys.org.uk/cgi-bin/mailman/listinfo/dnsmasq-discuss) if they would consider  adding those hostnames into the cache. 

Thanks for your PRs and we hope this will not prevent you from contributing in the future again.

**Pull request closed without merging**
