### PR TITLE
Use two different divs for mobile and desktop instead of a JS solution

### PR DESCRIPTION
**Pull request by Th3M3**
Signed-off-by: Th3M3 <the_me@outlook.de>
Co-Authored-By: XhmikosR <xhmikosr@gmail.com>

**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [ ] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

Reduce need of js code.

This replaces #1264.

**How does this PR accomplish the above?:**

Add a separate domain input form and toggle them depending on the screen's width.

**What documentation changes (if any) are needed to support this PR?:**

`-`

### CODE REVIEW

**Comment by XhmikosR** [comment]
Thanks for the PR, I haven't forgotten about it, I'll get to test it this week hopefully.

**Review by PromoFaux — DISMISSED** [review]

**Comment by PromoFaux** [comment]
Please resolve merge conflicts, thanks!

Proposed changes work well

**Comment by Th3M3** [comment]
@PromoFaux Ok, done.

**Comment by XhmikosR** [comment]
This should be simplified later. There's no reason for us not to use unique classes in the buttons.

**Review by DL6ER — APPROVED** [review]

**Pull request merged**
