### PR TITLE
Fixes background of the dark-midnight theme

### PR DESCRIPTION
**Pull request by xopez**
Signed-off-by: xopez <xopez@users.noreply.github.com>

**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

This PR fixes the background of the dark-midnight theme

**How does this PR accomplish the above?:**

Changing the background in CSS.

**What documentation changes (if any) are needed to support this PR?:**

Nothing I think.

This PR is a wished new PR. Discussion is found here: #1885

### CODE REVIEW

**Comment by xopez** [comment]
I think I misunderstood the signed off for DCO. And the warnings are still there.

**Comment by rdwebdesign** [comment]
Actually, you have 2 different failed tests:

The first one is **DCO**. 

> I think I misunderstood the signed off for DCO. And the warnings are still there.

The name and e-mail should macth your github profile information, but you used the wrong name and the wrong e-mail.
The error is explained [here](https://github.com/pi-hole/AdminLTE/pull/1961/checks?check_run_id=4142082698), at the end of the page.
```
Expected "Sascha Moser 28950736+xopez@users.noreply.github.com", but got "xopez xopez@users.noreply.github.com".
```
<br>

The second failed test is **CodeFactor**.

I don't know why this is happening now, but didn't happened before with this same file.
Maybe the old version was bigger and the test was skipped... I'm really not sure.

**Comment by PromoFaux** [comment]
Sorry, that was my fault with the DCO, I gave you the wrong text - however that's fine - I can set that to pass manually. I'll try to look later as to why CodeFactor is being so picky all of a sudden...

**Comment by DL6ER** [comment]
Added through https://github.com/pi-hole/AdminLTE/pull/1966

**Pull request closed without merging**
