### PR TITLE
HTML `hidden` attribute does not need a value.

### PR DESCRIPTION
**Pull request by XhmikosR**
Signed-off-by: XhmikosR <xhmikosr@gmail.com>

**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [ ] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**Untested**, but should be fine since that's the spec.

### CODE REVIEW

**Comment by PromoFaux** [comment]
Same comment here as per the PR for clearing filters. not sure just `hidden` is enough

**Comment by XhmikosR** [comment]
It's a boolean attribute so it should be enough. But something else could interfere with this.

**Comment by XhmikosR** [comment]
Converted to draft until we have a better understanding what's going on.

**Comment by XhmikosR** [comment]
I think the issues you are seeing @PromoFaux are present in devel too. Can you confirm so that we unblock this?

**Comment by PromoFaux** [comment]
Actually the button on the query log doesn't show up at all for me on `devel`

**Comment by XhmikosR** [comment]
Yup, so it's not related to this patch :)

That's what I'm trying to solve in #1299, but it's a general issue; we aren't supposed to use `hide()`/`show()`

>jQuery incompatibility
>
>[hidden] is not compatible with jQuery’s $(...).hide() and $(...).show() methods. Therefore, we don’t currently especially endorse [hidden] over other techniques for managing the display of elements.

It worked before because we were also using `btn`s wrong.

Anyway, that's something I want to address in a separate PR because it's something wrong that happened to work, and I hit it in the AdminLTE 3 branch too.

**Pull request merged**
