### PR TITLE
Back to top button

### PR DESCRIPTION
**Pull request by clwgh**
Signed-off-by: Chris L <github@holosys.co.uk>

## Thank you for your contribution to the Pi-hole Community! 

Please read the comments below to help us consider your Pull Request.

We are all volunteers and completing the process outlined will help us review your commits quicker.

**Please make sure you**
 1. Base your code and PRs against the repositories developmental branch.
 2. [Sign Off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits as we enforce the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions

---
- **What does this PR aim to accomplish?:**

This PR adds a floating "Back to top" button in the lower-right next to the scroll bar which can be used to return to the top of the page quickly. This avoids the need to locate and drag the scrollbar or use the keyboard and is especially useful on long pages such as a long Query log.

Ref forum feature request https://discourse.pi-hole.net/t/add-a-floating-back-to-top-button-for-long-pages/57860

- **How does this PR accomplish the above?:**

Button added to footer.php. Button is hidden until page scrolled down 20px and is then displayed. Code for scroll detection and scroll to top in footer.js. Button styling in pi-hole.css with per-theme tweaks to respect each theme. Tested on Safari/Mac, Firefox/Win, Safari/iOS and on all themes.

NOTE: LCARS theme has Group dropdowns and page numbers overlapping button if they coincide, tested against AdminLTE/PR#2405 but still appears present.

- **What documentation changes (if any) are needed to support this PR?:**

None

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
- [x] I have read the above and my PR is ready for review. _Check this box to confirm_

### CODE REVIEW

**Comment by clwgh** [comment]
This is my first proper PR. I'm not sure what happens next. Do I tweak the code formatting to confirm to the npm green text? If I do that in my local clone, do I issue a new commit and PR and it becomes absorbed into this one automatically, or does this need to be closed and I start over?

**Comment by yubiuser** [comment]
You can manually tweak the code to fit the "green text" or your run `npm install` followed by `npm run xo:fix` which will fix it automatically. After that you have new changes which you need to commit. After you committed locally, you push your changes (to your github remote repo). This PR will automatically sync with your github repo. 

No need to close/start over.

**Comment by yubiuser** [comment]
After the tests pass, one of us will review the code/idea when time permits.

P.S. If making changes to the interface repo, it's always nice to include screenshots in the PR here on github ;-)

**Comment by rdwebdesign** [comment]
I don't think we should add this button on the bottom right, like this.

image

On small screens (or even big screens not using the "boxed" layout), this will cover other elements.

This will look bad and it is a bad design decision, but there are alternatives.

We can move the button to the sidebar, but the button will appear only if the user scroll pass the menu height.
This will need a little more calculation. I will look like this:
back_button

Note:
You can start this moving the button to the  [`<aside>`  tag](https://github.com/pi-hole/AdminLTE/blob/master/scripts/pi-hole/php/sidebar.php#L280). You also need to change the CSS to center the button. Remove `right:30px` and add `width: 110px; margin: 0 60px;`.

**Comment by clwgh** [comment]
Thanks yubi for the redo info, and rdwebdesign for the feedback. What about the sidebar in the location shown in the forum post (linked in PR)? That space is always visible, either expanded or collapsed into a column. It can be made to appear only once the menu has scrolled out the way. Shall I tweak to make it appear there and adjust the activation?

I liked the idea of keeping the button near to the scrollbar since it's an alternative to interacting with the scrollbar, but I too was put off a little by it overlapping delete/white/blacklist buttons in a compacted view. Hence going with a translucent effect changing to solid on mouseover. However it seems that is where most people expect to find it. The button on Pi-hole docs is centered at the top and opaque; I like that look too but it interferes with the dashboard and control elements if its activation isn't carefully managed.

**Comment by rdwebdesign** [comment]
On the Docs the left and right always have links. Docs uses the button on the center, because there are almost only text there.

Personally, I really think a button covering other controls is bad. 
Also, if the button is near the scrollbar, I can use the scrollbar. I think this button is mostly used on mobiles/touch devices and its placement is not necessarily tied to the scrollbar.

**Comment by clwgh** [comment]
Thanks, I'm inclined to agree, I'm not keen on the idea of control elements with different functions pushing together depending on layout. In use it's been working well here but in principle it still bothers me. Re the scrollbar I find this most useful if moving a long way down a long query log to locate something. The button saves having to go to the keyboard, having to use a scroll wheel for 30 seconds or having to locate and drag the scroll bar up. On the iPad the effect is reduced since it has its own browser-wide touch controls, hence would be better out the way as you say.

**Comment by rdwebdesign** [comment]
Some tests are failing (don't worry).
In this case, the problem is just code format. You need to make the changes shown on the test details.

You can find exactly what is failing on each test clicking on "Details" button:

image

**Comment by clwgh** [comment]
Code reformated to test details. Do you want me to do another PR or shall I first move the button into the sidebar and change the trigger and styling to match and do it all in a oner? Again please forgive me, first time using GitHub and git for code so not been through this process before, unsure of the usual workflow, what happens next etc

**Comment by rdwebdesign** [comment]
> Again please forgive me...

No need for that.

> Do you want me to do another PR or shall I first move the button into the sidebar and change the trigger and styling to match and do it all in a oner?

You can do any changes you like and commit again (on the same PR).

**Comment by clwgh** [comment]
Thanks, my primary concern is messing something up and causing cleanup work for you or for me. I've read some horror stories requring painful looking git commands to unpick. I'll play with the button position and style tomorrow and see if I can make it sit referenced to the sidebar area instead of the browser window, along the lines of the mock up in my original forum post.

**Comment by rdwebdesign** [comment]
>  I'll play with the button position and style...

I tried putting the button inside the `<aside>` tag and also right after this tag. Maybe the second one will make it easier to adjust the position on mobiles.

You are displaying the button if the user scrolled `20px`. 
This could make the button cover part of the menu, in cases where the window `height` is smaller than the menu. 

I got it working if a different calculation:

```js
  var menuBottom = $(".sidebar").offset().top + $(".sidebar").outerHeight(true);
  var offset = $(window).scrollTop() + $(window).innerHeight() - menuBottom;
  if (offset > 85) { // The button height is 90px, but 85 will work since we have some padding on the sidebar
     ...
```

This will show the button only when the user scrolls enough to fit the button under the menu.

**Comment by clwgh** [comment]
> Maybe the second one will make it easier to adjust the position on mobiles.

That looks promising, I'll test it on desktops, iPhone and iPad.

> You are displaying the button if the user scrolled `20px`. This could make the button cover part of the menu

Yes this worked okay with the button transparent and at the bottom but not good while it's on top of menu items. I'll explore your calculation to make it stay quiet until the menu has scrolled out the way.

I'll also test how it looks with sidebar expanded vs closed. I'm thinking a smaller square up arrow style might work nicer across both cases. But I'll try to get it working at all first then play with styling.

Thanks. Now I just need to resist urge to "just try it out for 5 mins before bed", which turned into an enjoyable all-nighter last time I thought that :-)

**Comment by yubiuser** [comment]
Tests did pass now, why did you close?

**Comment by clwgh** [comment]
I messed up github and my clone somehow and couldn't understand how to fix it or what was going on with one error after another. This PR is closed, I'll start over if I'm able to get a revised button working in the sidebar.

**Comment by yubiuser** [comment]
Ok, don't give up.

**Comment by clwgh** [comment]
Thankyou, I won't give up but it's clear that I need to understand git and github's full terminology and correct workflows, step by step, if I'm to resolve any consistency issue that comes up in future. It was okay until I broke it. My clone and repo were leapfrogging each other by 1 commit back and forth no matter what I did, and I had errors trying to update my fork to your updated devel branch. Not sure if I use sync, or do PRs, or even if I can ever delete my fork of your repo once I've contributed without losing everything. Not even sure what the differences are with sync, PR, etc. All things I need to skill up on. The button code is a separate thing, looks like I can keep it references in the footer.php but the styling is what's needed to position it in the sidebar, but trying to work out how that ties into rd's code, so I'll be trying that out. Thanks for your patience.

**Comment by yubiuser** [comment]
When our `devel` updated your need to update your fork by `pulling` from our repo. Afterwards you need to checkout your feature branch and rebase on the "new" `devel` state. Then push (force) the rebased branch to your github repo.

**Comment by rdwebdesign** [comment]
Did you saw the github message about your branch is outdated and decided to update the branch?

My suggestion is to ignore this message until your work is done (unless you are already comfortable with `git` commands). You can try to update the branch in the end.

**Comment by rdwebdesign** [comment]
I think your code was in the right direction.

> The button code is a separate thing, looks like I can keep it references in the footer.php but the styling is what's needed to position it in the sidebar, but trying to work out how that ties into rd's code, so I'll be trying that out. Thanks for your patience.

You can leave the button on `footer.php`, but my suggestion is to move it to the end of `sidebar.php`. This will make it easier to position the button when the sidebar is collapsed (will need less CSS).

**Comment by clwgh** [comment]
Spent a few hours on this today, I can't get this button to behave. A combination of not knowing enough about how Pi-hole's UI is structured, and me not knowing enough ninja CSS. What I want seems simple:

- Button appears in sidebar after Donate has scrolled off top of screen
- Or in collapsed sidebar after Donate icon has scrolled off top of screen
- Button stays fixed floating in that area, a few px from top and right of sidebar edge, whether expanded or collapsed, as page scrolls down
- Button stays fixed distance from right edge of sidebar such that when sidebar is collapsed the button is already centered. You can see this isn't right in the screenshots below

What happens:
- Button scrolls with sidebar, or else is fixed to upper left of browser window outside sidebar
- Button stops being fixed when sidebar is collapsed or just doesn't render at all
- Detecting n px down to activate once Donate has scrolled off seems lame (using 200px so far, still not enough), must be a cleaner way

Tweaks that work
- Replaced the text with a up arrow `&uarr;` which looks nicer and fits in the sidebar collapsed. Anything wider doesn't work well with the collapsed sidebar.
- Ditched the transparent effect since that was only relevant for floating over text. Now it's solid and changes brightness when hovered. Will be tweaked for each theme once working. Gives good consistent styling across themes.
- I've moved the button from footer.php to sidebar.php at the end within `<aside>`

button

button2

Please let me know:
- If you like the up arrow button, and if not, what approach would you want for the collapsed sidebar which seems too narrow for any text
- If this sidebar location is working for you or if you want the button somewhere else

**Comment by yubiuser** [comment]
> If you like the up arrow button, and if not, what approach would you want for the collapsed sidebar which seems too narrow for any text

Personal taste: if expanded, the button should be bigger and shrink when the menu collapses. It should be even smaller than it is in your screenshot right now.

> If this sidebar location is working for you or if you want the button somewhere else

I need to test this a few days on different devices. My feeling tells me, I prefer to have it on the right side of the screen (as with the scroll bar), but I might get convinced to put it in the sidebar after trying it.

**Comment by yubiuser** [comment]
> I need to test this a few days on different devices.

P.S. I need a PR, so I can checkout the pull request and see how it feels.

**Comment by rdwebdesign** [comment]
> If you like the up arrow button, and if not, what approach would you want for the collapsed sidebar which seems too narrow for any text

We can decide the final button format latter. I personally think the best idea is to use "Back to top + an arrow" for the normal button and hide the text (leaving only the arrow) on the collapsed bar.
We can tweak the position on mobile too, if needed.

Screenshots are very good, but if you want to proceed with this PR, we will need to access the actual code.

**Comment by clwgh** [comment]
> if you want to proceed with this PR, we will need to access the actual code

I don't have code to give you; I can't make the button float consistently in the sidebar, or even float/appear at all when collapsed. I'm trying to reverse engineer how the screen sections are defined and put together so I can home in on the correct css to position it. I posted the above to see if this placement is worth the research.

> My feeling tells me, I prefer to have it on the right side of the screen

Me too but there's nowhere to put it without risking it moving into other other buttons. The transparent overlay was the first attempt at trying to resolve that conflict and it works for me but is not good practice as RD suggested. The sidebar seems the only logical place that guarantees an unconflicted space for it. The top center (like the docs) sort of works but then gets in the way on screens such as Dashboard.

**Pull request closed without merging**
